### ISSUE TITLE
[android] kodi crash after playback start

### ISSUE THREAD

**Issue by gd71** [Sandmann79/xbmc#120]
Hello,
not sure if related to Amazon VOD or inpustream but here is what I get each time I try to start a playback on kodi 18 last builds:
 
13:00:09.730 T:2089048832  NOTICE: [Amazon VOD] https://s3-dub.cf.dash.row.aiv-cdn.net/dm/2$U8oyDJS2ycxNXGktkwTgR736mVs~/2d2d/8cd5/159c/471a-b550-fbfc975ed3c3/8dfcb260-46ec-48ae-8ef6-0ff03f12f521_corrected.mpd
13:00:09.770 T:2089048832  NOTICE: [Amazon VOD] Using inputstream.adaptive Version:2.2.16
13:00:09.819 T:2089048832  NOTICE: [Amazon VOD] Checking AudioTrack
13:00:09.907 T:18446744072444036736  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2F%2F-Films-%2F%2F-Films+populaires-//-0GDNZSM9LHLVJXQ915BLH1CL6W
13:00:09.914 T:2114149376  NOTICE: Creating InputStream
13:00:10.152 T:2114149376   ERROR: AddOnLog: InputStream Adaptive: Key system request: com.widevine.alpha
13:00:13.000 T:18446744071819120896   ERROR: SOCK: Error selecting socket(s)
13:00:13.000 T:18446744071819120896   ERROR: ES: Exception caught while listening for socket
13:00:13.000 T:18446744071819120896  NOTICE: ES: UDP Event server stopped
13:00:16.250 T:18446744071819120896  NOTICE: ES: Starting UDP Event server on port 9777
13:00:16.252 T:18446744071819120896  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
here is the full log
https://ares-project.uk/logupload/log.php?id=127659
Using amazon app for android is not an option for me 
please note also that filling the database for the first time could take around 30 minutes.
Thanks for your feedback

**Comment by Varstahl** [comment]
Hmm, it's strange, it seems like the addon is providing everything correctly but the video playback isn't really working due to some connection error. I'm not ultra familiar with android deployment or status of kodi.

Just a couple questions: if you try multiple times does it still refuse to work? If you try to specify a different CDN provider (from addon settings `General > Prefered Host`) do you still have the same problems?

**Comment by gd71** [comment]
Hello,
Of course I've tested several times before raising the issue
currently testing other providers with no luck, same behavior.
Others plugins using inputstream seems to work fine (youtube, twitch..)
I've also issue with netflix, will check if logs are similar but in the case of netflix, there is no crash but nothing (maybe network error is handled on plugin side)
This morning, database had to be refreshed, it took 2 hours, it's anyway not usable at all on my android tv lollipop ARM V7 (32b)

**Comment by gd71** [comment]
Netflix issue is related to wrong KID/key request not successful, I guess it's another story

**Comment by gd71** [comment]
Note also that the plugin is working just fine on my linux box with same kodi release

**Comment by Varstahl** [comment]
I just noticed: there is something quite very wrong with what the addon is doing: `NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/…` this should display the URL request of the video instead. The link there is wrong. You mentioned you had to refresh the database, did you export the video db from the addon? Does it work if you just go browse from within the addon itself?

I never looked at the PrimeVideo export of videos, it's something Sandmann managed, and since I never used I didn't even test it. Could you provide more information about how you're using the addon?

**Comment by gd71** [comment]
No I never used this feature, Custom export folder is deactivated in the settings but create video information file is set to true.
The (what I call ) refresh of db is done by browsing within the addon, first to find categories and when selecting one category
Playback with : inputstream
DRM check fallback to None

**Comment by gd71** [comment]
refreshing behavior is:
Select a category
busy animation 15 seconds
display "Amazon VOD found <a film title>
Busy animation 15 seconds
Display "Amazon VOD Loanding next page..."
busy animation 15 seconds
display "Amazon VOD found <another film title>
busy animation 15 seconds
repeatedly during hours

**Comment by Varstahl** [comment]
The wait for film titles in the notification is kind of fake, I can't display every single thing because Kodi can't keep up and doesn't discard previous notifications, so you'd be watching a movie while 3-4 hours of notification would keep popping up. What you describe is strange though, even admitted you have a very slow connection speed it shouldn't take two hours and it absolutely shouldn't repeat itself, the video data is perma-cached after the first scraping, so in your case every single movie you already found should be cached and loaded much faster. I don't currently have an android box, stick or whatever to test it so for the moment I can't really know what's going on.

It might be a bad build doing weird stuff (it's alpha so it's very possible), or something else entirely. I'll try to find something to test it with as soon as I can.

**Comment by gd71** [comment]
I've got a quite good connection around 50 Mb/s (VDSL) and I always watch streams in HD.
Thanks anyway for having a look at this.
If I find any other interesting information, I'll post it there

**Comment by Varstahl** [comment]
Good to know. I'm ultra busy with the incoming GDPR deadline, haven't had time to play around with ARMs yet.

**Comment by locoguano** [comment]
Same issue on Amazon Fire TV.
https://pastebin.com/e4YePUTb

**Comment by Varstahl** [comment]
I don't know if you're still interested, and it's been several months already, but with latest PrimeVideo fixes the speed while loading from the cache have improved a lot. On top of that Kodi published a number of fixes and is way more stable in its current form. Have problems been solved/abandoned or do you still need assistance?

**Comment by Varstahl** [comment]
Closing for aging and inactivity.
