### ISSUE TITLE
Unable to load prime video

### ISSUE THREAD

**Issue by TheSecEng** [Sandmann79/xbmc#121]
Running on Raspberry Pi 3 B
Latest OSMC

Latest Add-on here. Insert prime credentials and receive

'PrimeVideo error', 'Unable to find the main primevideo.com navigation section' 

What is the main cause of this?

**Comment by Varstahl** [comment]
That could either be a temporary error or Amazon breaking the home page again.

In order to have the latest and correctly localized home menu, the addon parses the PrimeVideo homepage main navigation, shown here:

![Main navigation](https://user-images.githubusercontent.com/284077/39879068-2b77e488-547a-11e8-8c7c-f54282c6116a.png)

From here it gathers the Movies, TV Series and Kids sections, and starts the scraping. If you didn't have problems before, it might be just a temporary problem on Amazon's servers that they will fix in due time (has happened before), or they somehow changed the navigation system on the page for your area (also possible), or something broke while trying to build the root catalog and it's the addon fault (never happened so far but still possible).

To exclude the addon's fault I should take a look at some parts of the logs you can find in `%AppData%\Kodi\kodi.log` or the *nix equivalent `~/.kodi/temp/kodi.log`, that you can post somewhere like [pastebin](https://pastebin.com/). To exclude Amazon's fault I should take a look at the HTML generated for your country: simply go to [https://www.primevideo.com/](https://www.primevideo.com/), hit CTRL+U, and copy paste the HTML somewhere like pastebin (linked previously).

Or it could just be a connection problem, and if you're sure the connection is actually working, just try starting the addon a few more times, it might just work if it was a case of DNS/Connection hiccup.

**Comment by sky7176** [comment]
I have the same problem, Amazone video not started, I use Kodi 18 beta.

this is my log
1:47:29.966 T:1433379696  NOTICE: [Amazon VOD] Using Host: Cloudfront
21:47:29.976 T:1433379696  NOTICE: [Amazon VOD] checkURL: https://s3-dub.cf.dash.row.aiv-cdn.net/dm/2$YoTm9zGkdT2gy90vCM04DJmgnZ8~/9823/67f1/f007/4b83-9033-100731c65071/b2202bb9-90ef-4a3e-94e5-c730c51dc4d2_corrected.mpd
21:47:30.764 T:1433379696  NOTICE: [Amazon VOD] Using inputstream.adaptive Version:999.2.2.16
21:47:30.875 T:1433379696  NOTICE: [Amazon VOD] Checking AudioTrack
21:47:30.913 T:0  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2F%2F-Film-%2F%2F-Film+%E2%80%93+Azione+e+avventura-//-0FFLMNHL25OTTBMQRWJXX0DDX4
21:47:30.914 T:0 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED

I used input stream

**Comment by Varstahl** [comment]
@sky7176 that's an entire different problem, the movie and the addon work fine, there's something wrong in your installation, the reported version of IS.A on your logs is `999.2.2.16`. Maybe a bad Kodi nightly build?

**Comment by sky7176** [comment]
This a last log

23:15:37.788 T:1945108592   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
23:15:40.639 T:1389224864  NOTICE: [Amazon VOD] Version: 0.5.4
23:15:40.640 T:1389224864  NOTICE: [Amazon VOD] Unicode filename support: False
23:15:40.640 T:1389224864  NOTICE: [Amazon VOD] Locale: en-gb / Language: it
23:15:58.813 T:1389224864  NOTICE: [Amazon VOD] Using Host: Akamai
23:15:58.824 T:1389224864  NOTICE: [Amazon VOD] checkURL: https://a264avoddashs3ww-a.akamaihd.net/d/2$n8W7skL7AyZLbZp_icXAcA9io7c~/ondemand/dub-dub-iad/83a4/7367/d98e/4e04-918c-3cb9d90c68a9/cd118436-622f-40a3-8073-0c8940f960dd_corrected.mpd
23:15:59.701 T:1389224864  NOTICE: [Amazon VOD] getURL: https://a264avoddashs3ww-a.akamaihd.net/d/2$n8W7skL7AyZLbZp_icXAcA9io7c/ondemand/dub-dub-iad/83a4/7367/d98e/4e04-918c-3cb9d90c68a9/cd118436-622f-40a3-8073-0c8940f960dd_corrected.mpd
23:16:01.749 T:1389224864  NOTICE: [Amazon VOD] Using inputstream.adaptive Version:2.0.15.0
23:16:01.751 T:1389224864  NOTICE: [Amazon VOD] Checking AudioTrack
23:16:01.817 T:1945108592  NOTICE: VideoPlayer: Opening: https://a264avoddashs3ww-a.akamaihd.net/d/2$n8W7skL7AyZLbZp_icXAcA9io7c/ondemand/dub-dub-iad/83a4/7367/d98e/4e04-918c-3cb9d90c68a9/cd118436-622f-40a3-8073-0c8940f960dd_corrected.mpd
23:16:01.817 T:1945108592 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
23:16:01.818 T:1406002080  NOTICE: Creating InputStream
23:16:01.990 T:1406002080   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
23:16:03.058 T:1406002080   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (https://a264avoddashs3ww-a.akamaihd.net/d/2$n8W7skL7AyZLbZp_icXAcA9io7c/ondemand/dub-dub-iad/83a4/7367/d98e/4e04-918c-3cb9d90c68a9/cd118436-622f-40a3-8073-0c8940f960dd_corrected.mpd)
23:16:03.065 T:1406002080   ERROR: CVideoPlayer::OpenInputStream - error opening [https://a264avoddashs3ww-a.akamaihd.net/d/2$n8W7skL7AyZLbZp_icXAcA9io7c/ondemand/dub-dub-iad/83a4/7367/d98e/4e04-918c-3cb9d90c68a9/cd118436-622f-40a3-8073-0c8940f960dd_corrected.mpd]
23:16:03.065 T:1406002080  NOTICE: CVideoPlayer::OnExit()
23:16:03.066 T:1945108592   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2F%2F-Film-%2F%2F-Film+%E2%80%93+Azione+e+avventura-//-0LGZZZWJYDTI9PLD2VE8NZY0DK]
23:16:03.091 T:1945108592  NOTICE: CVideoPlayer::CloseFile()
23:16:03.091 T:1945108592  NOTICE: VideoPlayer: waiting for threads to exit
23:16:03.091 T:1945108592  NOTICE: VideoPlayer: finished waiting
23:16:03.092 T:1945108592  NOTICE: CVideoPlayer::CloseFile()
23:16:03.092 T:1945108592  NOTICE: VideoPlayer: waiting for threads to exit
23:16:03.092 T:1945108592  NOTICE: VideoPlayer: finished waiting

**Comment by Varstahl** [comment]
@sky7176 scusami se ho cancellato i tuoi interventi, ma non puoi dirottare delle issue altrui con le tue, specialmente quando sono due problemi completamente diversi. Inoltre, se avessi tentato di cercare, ti saresti accorto del fatto che la tua problematica è descritta nella issue #90. Trovi ulteriori informazioni lì.

**Comment by sky7176** [comment]
Bruno, non ti devi scusare.
Onestamente mi sono agganciato al primo topic con issue che mi sembrava simile alla mia.
Guarderò la issue che mi hai indicato e vedrò di capire il perchè non mi funziona.

Giuseppe

PS. volevo scriverti in privato ma non ho trovato come fare, elimina pure questo post.

**Comment by Varstahl** [comment]
Closing this as it's already a month old with no further feedback.
