### ISSUE TITLE
Where are subtitles?

### ISSUE THREAD

**Issue by mirh** [Sandmann79/xbmc#123]
I don't know if it might not be inputstream's or latest kodi nightly's fault.. But why should I have to like download separately subs? Instead of just having them neatly available from start, like audio. 

EDIT: just noticed that if I set "subtitles preferences" from *none* to just about anything else, they get finally selected. They don't display though.

**Comment by Varstahl** [comment]
There are a few outstanding problems with subtitle streams, so the current workaround/method is to download the subtitle streams to disk to then let the user properly display them. In order to keep the bother to a minimum, there are various different settings to suit everybody's need. The subtitle settings are set in both the addon and the `Kodi Settings > Player > Language`.

The main Kodi options are:
* None
* All
* From Kodi player language settings
* From settings, fallback to english
* From settings, fallback to all

So, let's suppose you have subtitle language in Russian. The first option never downloads subtitle, the second option downloads all subtitle regardless of what you chose in the player language settings, the third option downloads your preferred subtitle language, if available, while the last two options set options for fallback in case your language is not available as a subtitle stream, so falls back to English or to download them all.

There is the additional (hidden?) option of forced narrative. Forced narrative are particular reduced subtitles, aimed at providing subtitles where the actors speak a different language, and are also provided by Amazon. So if forced narrative subtitles are provided for your language, you can select `Forced only` in the Kodi player language settings, and then one of the subtitle download options except, of course, None. More on the forced subtitles can be found in #113.

**Comment by mirh** [comment]
Yes, but (understanding now whatever these outstanding problems may be) the thing is, that even after going manually looking for them they aren't working. 

Or better, I just now managed to see them appearing.. ***if*** they are automatically showed from the beginning of the video, but as soon as I change them, or go rewind/fastforward they totally go nuts.

**Comment by Varstahl** [comment]
That has nothing to do with the addon. I had similar issues on previous Kodi builds, but it seems to work fine as of the couple different builds I have updated about a month ago or so. The addon doesn't manage audio, video nor subtitles, it only provides them for Kodi, and Kodi manages everything else. What you mentioned sounds a lot what I was experiencing in early alpha builds from around January, iirc. Try updating Kodi to one of the latest nightly builds.

**Comment by mirh** [comment]
I *am* using latest nightly..

**Comment by Varstahl** [comment]
Very, very weird

**Comment by Varstahl** [comment]
Closing this as the relevant information are now inside the [FAQ](https://github.com/Sandmann79/xbmc/wiki/FAQ#how-can-i-select-the-appropriate-subtitles--where-are-my-subtitles).
