### ISSUE TITLE
Hard crash if Browser is selected in Windows

### ISSUE THREAD

**Issue by natethomas** [Sandmann79/xbmc#130]
Running a recent copy of Kodi 18 and addon downloaded today. https://pastebin.com/Pi3S3rQL

I didn't realize you had to switch to adaptivestream from browser. After I did, everything worked great. I'd suggest either defaulting to adaptivestream or putting in a function to catch whatever causes the break and giving a warning.

**Comment by Varstahl** [comment]
Huh, that shouldn't happen, I'll give it a look. Thanks for the feedback.

**Comment by Varstahl** [comment]
I've been running a few tests, and while I had one case in which Kodi crashed, it was due to some problems in Kodi's code rather than the addon itself.

In your case it's not even a problem of crashing, rather stalling:
```
11:23:05.300 T:48276   DEBUG: CIRServerSuite::Connect: connecting to: 127.0.0.1:24000 ...
11:23:06.302 T:48276   DEBUG: CIRServerSuite::Connect: failed to connect
11:23:06.302 T:48276    INFO: CIRServerSuite::Process: failed to connect to irss, will keep retrying every 5 seconds
```
and this goes on and on, stalling the backend, meanwhile:
```
11:23:34.304 T:51324   DEBUG: Thread JobWorker 51324 terminating (autodelete)
11:23:34.309 T:39156   DEBUG: Thread JobWorker 39156 terminating (autodelete)
11:23:34.322 T:33472   DEBUG: Thread JobWorker 33472 terminating (autodelete)
11:23:34.323 T:14504   DEBUG: Thread JobWorker 14504 terminating (autodelete)
```
causing the hard freeze of the application.

So unless I missed something in my testing, Kodi has some fixing to do and/or CIRServerSuite must be adjusted/reconfigured. In any case it doesn't look like the addon's at fault.
