### ISSUE TITLE
Considerably slow loading of video listings

### ISSUE THREAD

**Issue by jmaris** [Sandmann79/xbmc#141]
Hey,

I'm on a Raspberry Pi on the latest Kodi, I've noticed it takes a very long time to load video listings (sometimes multiple minutes). I was wondering if this is normal or if there is something wrong on my end ?

Thanks again for the Brilliant Plugin !

**Comment by jmaris** [comment]
Hey, It's the rPi 3 so CPU usage shouldn't be that much of an issue, i'll try loading a category with htop to watch CPU usage ! as for network speed it isn't half bad( 30mbit/s), and yes, on the second time it loads much much faster :)

Thanks, i'll get back to you regarding CPU usage, that could well be the bottleneck

**Comment by Varstahl** [comment]
The latest kodi builds are improving speed and response time, I've noticed huge improvements on the PC front, those might help as well.

**Comment by mo123** [comment]
Takes almost 15 minutes to Open the Movies section then a Movie category on Android Nougat with Kodi 18 A3.
Is there a way to improve the speed or a setting that can be changed to load less items?
Second time is a bit faster but also longer than 5 minutes.
Other addons open instantly.

**Comment by Varstahl** [comment]
There's only so much that can be done when you have to parse 50-100 pages of results on the fly. The first time you load any category it will take at least twice as much if not more, due to the additional information required from different sources. I adopted all the tricks of the trade to reduce the time necessary to parse a list, like connection pooling, but a slow processor speed will hinder that, and there's little to nothing that can be done.

I could maybe keep Amazon's standard pagination as an option, but it's gonna be low in the priority list.
