### ISSUE TITLE
Kodi 18 Alpha 2 : Plugin Crashes Kodi after inputting Password

### ISSUE THREAD

**Issue by Ltek** [Sandmann79/xbmc#146]
I just installed this plugin for the first time. I'm using Kodi 18 Alpha 2

It installed fine, and lets me put in my Amazon user name but when it gets to the password, I input the PW and then the entire Kodi crashes after the plugin errors out.

Anyone else seeing this?

**Comment by Varstahl** [comment]
Yes, another user reported a similar issue. Kodi has seen major changes in several parts, you need to update to the latest nightly available. It currently sits in Alpha 3.

Due to changes in the Widevine DRM, even if Kodi didn't outright crash it wouldn't work anyway, the fixes and changes have been pushed to main in a later version than what you're currently using.

**Comment by Ltek** [comment]
Alpha 3 - I don't think so? Only Alpha 2 is posted, and nightly builds. I'll try a nightly. thx

**Comment by Varstahl** [comment]
> Alpha 3 - I don't think so?

![Alpha 3](https://user-images.githubusercontent.com/284077/42310297-57cdfb98-803b-11e8-9ecf-37f9c7ade108.jpg)

**Comment by Ltek** [comment]
Alpha 3 is not officially in pre-release status... After each pre-release is official, the next nightly builds are will 'track' to the next pre-release, in this case Alpha3.  I'll test out the build from last night. Thx

![capture](https://user-images.githubusercontent.com/1626802/42338034-c135505e-8045-11e8-8ac0-44e98395f948.JPG)
