### ISSUE TITLE
Error listing series

### ISSUE THREAD

**Issue by DanySK** [Sandmann79/xbmc#149]
Hi,
When I click on a season of any TV series, I get a notification with the name of first 2-3 episodes, followed by an "Amazon VOD Error, check the log for more information". I looked at the log and found:
```
00:16:19.654 T:140656385865472   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'encode'
                                            Traceback (most recent call last):
                                              File "/home/danysk/.kodi/addons/plugin.video.amazon-test/default.py", line 3387, in <module>
                                                PrimeVideo_Browse(None if 'path' not in args else args['path'])
                                              File "/home/danysk/.kodi/addons/plugin.video.amazon-test/default.py", line 487, in PrimeVideo_Browse
                                                url += 'PrimeVideo_Browse&path={0}-//-{1}'.format(urllib.quote_plus(path.encode('utf-8')), urllib.quote_plus(key.encode('utf-8')))
                                            AttributeError: 'NoneType' object has no attribute 'encode'
                                            -->End of Python script error report<--
```
How can I better help to frame the issue?

**Comment by Varstahl** [comment]
Hmm, that is very strange. The code base is going through a huge refactorisation atm so I can't pinpoint the problem exactly (to be read as _I might have already fixed it but forgot about it in the 7k+ loc changed in the last two days_). Given what I can see from the little log snippet, at a first glance, I'd say Amazon fucked it up again. But you say that happens on every series, which is incredibly unlikely. In order to address this I'll probably need some information:

* are you using the latest nightly build available, or are you using Alpha2, or Kodi17?
* can you tell me a tv series which is causing you the issue?
* what OS/distro are you using?
* what version of Amazon VOD are you using? 0.5.4 or one of our latest nightlies?

If you can post the log file on pastebin/gist I could take a look at it, that would greatly help. Oftentimes these kind of problems were related to incorrectly configured/routed VPNs, or to other addons conflicting in some way. It's hard to have a clear idea of the causes without a clear picture of everything that happened before the error occurred.

As a stupid _have you tried turning it off and on again_ test, maybe something initialised wrong and is now cached and giving troubles, so you could delete  `PVCatalog<MarketplaceID>.pvcp` and `PVVideoData<MarketplaceID>.pvdp` from `~/.kodi/userdata/addon_data/plugin.video.amazon-test`. If the problem was indeed cached, this could fix it.

**Comment by DanySK** [comment]
Hi @Varstahl,
in answer to your queries:
* Version (from log) is: 18.0-ALPHA1 Git:20180710-nogitfound
* A couple of examples (the first in alphabetical order) are "Absentia" and "All or nothing". Both season 1. I have not tried every serie of course, but I was not able to play any.
* Antergos (Arch) Linux, kernel 4.17.5-1-ARCH #1 SMP PREEMPT
* Version is reported as 0.5.4 inside kodi.
* I've tried to reboot, no result
* I deleted the files you suggested, rebooted kodi and tried again. The series list was re-downloaded (of course), but the error persisted.
* You can find an example log [here](https://pastebin.com/EU3gdQGq).

Thanks

**Comment by Varstahl** [comment]
> * A couple of examples (the first in alphabetical order) are "Absentia" and "All or nothing". Both season 1. I have not tried every serie of course, but I was not able to play any.

Everything seems in order from Italy, so I'd exclude a problem with the servers and by proxy (potentially) with the addon.

> * Version (from log) is: 18.0-ALPHA1 Git:20180710-nogitfound

This could be the main problem. I see for example things like this in the log:

```17:26:00.048 T:139995041804288   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed```

On top of that, due to changes with WidevineCDM and InputStream.Adaptive, I believe that even if it had no problems, versions lower than the current ALPHA3 (nightly) are not able to playback the videos on some platforms.

If you need to compile it yourself, [here's a guide on Kodi for Arch compilation](https://kodi.wiki/view/HOW-TO_compile_Kodi_for_Linux_on_Arch/Manjaro), and here's the [general linux guide](https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md). Keep in mind that in order to have everything working correctly, you need to compile both Kodi and the [binary addons](https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md#5-build-binary-add-ons).

I believe that with the proper Kodi update the problem should disappear by itself, but if that's not the case let me know and I'll spin an Arch VM.

**Comment by DanySK** [comment]
Thank you. I believe I can install the latest on Arch by modifying (this public PKGBUILD)[https://aur.archlinux.org/packages/kodi-git/].
Looking at tagged versions, I see the latest is (18.0a2-Leia)[https://github.com/xbmc/xbmc/releases/tag/18.0a2-Leia]. Should I just build the current master instead?

**Comment by DanySK** [comment]
Hi, I tried with the current master, version is marked as `18.0-ALPHA3 Git:20180712-91822241d1f` in [the log file](https://pastebin.com/1aLdrpWR). Problem persists. What I have done precisely:
* Installed Kodi from the AUR via AUR helper (I had to modify the PKGBUILD to get it to package, there is an error that needs to get fixed on the license file name in the PKGBUILD).
* Deleted `PVCatalog<MarketplaceID>.pvcp` and `PVVideoData<MarketplaceID>.pvdp` from `~/.kodi/userdata/addon_data/plugin.video.amazon-test`
* Updated (through AUR) Inputstream.Adaptive to 2.2.24 (was 2.2.22, incompatible with alpha 3).
* Fired up Kodi
* Tried to list the content of (sorry for writing in Italian, the plugin uses - I guess - the language for amazon.it because of my current location, should be easy to understand though) `Serie TV` -> `Serie Prime Original` -> `Absentia` -> `Stagione 1`. Notification appears for the first couple of episodes, then the error is raised.

I tried to list and play movies (Ace Ventura and Fight Club). Both work like a charm.

**Comment by Varstahl** [comment]
Don't worry about the italian, I'm italian as well so it's no big deal. In regard to your problem, yours is the first so far that wasn't fixed updating Kodi, so there's either something wrong with the version of the addon that I don't know yet (or that I forgot I fixed in the nightly), or it might be Arch specific. I'll recompile my Debian version asap, and see if I can reproduce the error.

> sorry for writing in Italian, the plugin uses - I guess - the language for amazon.it because of my current location

Outside of DE, JP, UK and USA, all the countries use PrimeVideo.com. The addon is language agnostic, it's the amazon servers providing the text in the language you choose (or the default for your country, if unspecified).

**Comment by Kal42** [comment]
Hi, I have the same problem (movie is working, only tv serie is not working), but the error is different :

> 08:32:04.606 T:1448080112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'ao\xfbt'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 83, in EntryPoint
                                                g.pv.Browse(None if 'path' not in args else args['path'])
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 169, in Browse
                                                self._LazyLoad(node, nodeName)
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 545, in _LazyLoad
                                                if None is not res[3]: meta['videometa']['premiered'] = DelocalizeDate(amzLang, res[3])
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 325, in DelocalizeDate
                                                p[self._dateParserData[lang]['month']] = self._dateParserData[lang]['months'][p[self._dateParserData[lang]['month']]]
                                            KeyError: u'ao\xfbt'
                                            -->End of Python script error report<--
08:32:04.778 T:1448080112 WARNING: CPythonInvoker(3, /home/osmc/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
08:32:04.789 T:1799238384   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2f%2f-S%c3%a9ries
08:32:04.792 T:1918078976   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2f%2f-S%c3%a9ries) failed

I have try to deleted PVCatalog<MarketplaceID>.pvcp and PVVideoData<MarketplaceID>.pvdp from ~/.kodi/userdata/addon_data/plugin.video.amazon-test, but still the same issue.

Thanks for you work.

**Comment by Varstahl** [comment]
@Kal42 yours seems to be a completely different issue, I moved it into #155. If you reply there I can start investigating your problem.

**Comment by Varstahl** [comment]
@DanySK the new Amazon VOD has been pushed to public, featuring a complete overhaul of the addon. Can you tell me if the problem has been fixed with it?

**Comment by DanySK** [comment]
Hi @Varstahl ,
tried today, everything smooth. Thanks for fixing this.
