### ISSUE TITLE
Amazon VOD "Unable to find the main primevideo.com navigation section"

### ISSUE THREAD

**Issue by lafreak88** [Sandmann79/xbmc#165]
Hallo guys

Saw this issue more often, but didn't find an answer.

Recent Kodi Beta with recent Amazon VOD Plugin

Here's the log

> 18:30:20.409 T:9124  NOTICE: My Music: Scanning for music info using worker thread, operation took 00:02
> 18:30:21.140 T:9148  NOTICE: VideoInfoScanner: Starting scan ..
> 18:30:24.561 T:9196  NOTICE: [Amazon] Args: {}
> 18:30:24.891 T:9196  NOTICE: [Amazon] AmazonDB: Service Start
> 18:30:30.300 T:9148  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:17
> 18:30:52.684 T:9148   ERROR: CCurlFile::FillBuffer - Failed: Number of redirects hit maximum amount(47)
> 18:30:55.003 T:9148   ERROR: Previous line repeats 1 times.
> 18:30:55.003 T:9148   ERROR: CAddonMgr: Failed to parse addons.xml.
> 18:30:55.049 T:9148 WARNING: Repository alelec Kodi Repo uses plain HTTP for add-on downloads - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> 18:32:14.794 T:2564 WARNING: Previous line repeats 3 times.
> 18:32:14.794 T:2564   ERROR: XFILE::CDirectory::GetDirectory - Error getting
> 18:32:19.695 T:7720   ERROR: Previous line repeats 6 times.
> 18:32:19.696 T:7720  NOTICE: [Amazon VOD] Version: 0.5.7
> 18:32:19.696 T:7720  NOTICE: [Amazon VOD] Unicode filename support: True
> 18:32:19.697 T:7720  NOTICE: [Amazon VOD] Locale: de-de / Language: de
> 18:32:20.432 T:7720   ERROR: [Amazon VOD] Unable to find the main primevideo.com navigation section

If you need more of this log let me know.

Christoph

**Comment by Varstahl** [comment]
PrimeVideo.com does not support Germany. Which country are you accessing it from?

This could either be a geolocation problem or a temporary dns timeout problem. If the second/third time you try it works, then it's a non-issue and most likely a dns problem. If you can't ever start the addon then I need more information, specifically your country of residence and the html dump from your browser of the primevideo.com homepage.

**Comment by Varstahl** [comment]
> oh then it was a misunderstanding. i thought the "amazon" add-on is just for germany, the VOD for every country.

Well, it is, but there's a problem somewhere, either with your connection or with your account. If you're using Amazon VOD and you're in Germany, Amazon VOD and the logs should point you to amazon.de, but it doesn't. That's done automatically, so if it doesn't then maybe you're behind a VPN of sorts?

> Now I have the next problem: Amazon Add-On don't show my watchlist.

There is absolutely nothing wrong in the logs, so maybe amazon.de doesn't actually have a watchlist?

I don't know, I'm speculating, there's surely something wrong somewhere in your connection or account. So, to recap:
* are you in Germany? If not what country are you browsing in?
* are you behind a VPN? PrimeVideo.com shouldn't be available to amazon.de, and since we check with Amazon directly, it must detect your location in error. A VPN in Canada or France perhaps?
* you say that neither addons detect your watchlist. Do you actually have a video watchlist on amazon.de?

**Comment by lafreak88** [comment]
okay i understand.
is it possible to change it manually?

I am in the Netherlands for my work, and it would be really nice to have amazon on Kofi. android app, browser, smart TV, fire TV, all of them are working without any problem. they all can read out the watchlist.

**Comment by Sandmann79** [comment]
To see your watchlist, you have to wait till the database update has finished on Amazon addon. This process can take up some hours.

The Amazon VOD addon supports manual region changing only in beta version. To install it, download the repo and extract the plugin.video.amazon-test folder to Kodis add-on folder and overwrite the existing one. After that choose as region Germany at settings>connection and enter your credentials.

**Comment by lafreak88** [comment]
perfect. working. thanks
