### ISSUE TITLE
How can I update Amazon VOD to 0.5.7 ?

### ISSUE THREAD

**Issue by pfugazzi** [Sandmann79/xbmc#172]
What's to dowload to upgrade the Amazon VOD to  0.5.7?

**Comment by Varstahl** [comment]
If you installed the repository in Kodi you can just update Amazon VOD through the addon management section. Or did you mean something else in particular?

If you just want the zip, you can find it in the repo, [here](https://github.com/Sandmann79/xbmc/tree/master/packages/plugin.video.amazon-test).

Also note that if you want to update because the addon broke, 0.5.7 won't help, you'll need to update *and* take a file currently in beta as described [here](https://github.com/Sandmann79/xbmc/issues/170#issuecomment-425657873).

**Comment by Varstahl** [comment]
0.5.8 with latest fixes released with 5f6b4229f41491578e2dc2cd9e989f378ce55690, available now on Kodi.
