### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by sheldonmaschmeyer** [Sandmann79/xbmc#188]
Hi, this is more a feature request than an issue.
I was watching Man in High Castle, when they speak German or Japanese, I need English subtitles.
The subtitles are available using a web browser but not input stream (opensubtitles.org does not work very well). Can the subtitles be fetched from the source (Amazon)? I like the 5.1 sound but, for not 100% English content, or if watching a show in another language, I would appreciate English subtitles. I also have friends who are not 100% native English speakers who might appreciate subtitles as well.
Thank you for all the hard-work on this free add-on.

**Comment by Varstahl** [comment]
The feature is already there, but you need a bit of set up. You can read more in [my comment inside #123](https://github.com/Sandmann79/xbmc/issues/123#issuecomment-388550806), but long story short, what you're looking for is forced narrative. Inside `Kodi settings > Player > Language > Subtitles` you will find `Prefer subtitle language` that you must set to `Forced only`.

![forced narrative](https://user-images.githubusercontent.com/284077/46916605-25845c00-cfbd-11e8-9b94-e7555514ba7e.jpg)

Then, inside Amazon VOD, you can enable subtitles with different options, but for what you want to achieve you either want `From Kodi […] settings` or `From settings, fallback to english`.

![subtitles](https://user-images.githubusercontent.com/284077/46916680-1baf2880-cfbe-11e8-9194-92dc3a75fe8d.jpg)

With this done, the addon will download the available forced subtitles (if any) in the language specified in the audio language player settings (italian in my case, in the first screenshot) or, if they're not available and fallback has been enabled, in english if they're available.

What this means is that when forced narratives are provided, in Mr. Robot or The man in the high castle, they will be downloaded and shown when the actors speak a different language, but they're invisible otherwise.
