### ISSUE TITLE
Replace `mechanize` with `MechanicalSoup`

### ISSUE THREAD

**Issue by satmandu** [Sandmann79/xbmc#206]
Mechanize is not compatible with python 3.

Consider switching to https://github.com/MechanicalSoup/MechanicalSoup ?

**Comment by Varstahl** [comment]
Kodi is compiled against 2.7, and afaik there are no plans to move it to python 3. Which is the reason why we also had to "make do" with certain libraries that are available through Kodi's install mechanism.

Do you have any specific reason to suggest switching to MechanicalSoup (if it's even provided by Kodi)?

**Comment by satmandu** [comment]
One kodi 18 branches the kodi 18 nightly builds will be python 3 only as per this:

https://kodi.tv/article/kodi-v18-leia-rc1-new-hope

Only suggesting MechanicalSoup since mechanize appears to not be getting updated for python 3 support, and mechanicalsoup appear to be support aspects of mechanize & beautifulsoup while being supported for Python 2 & 3 and also being actively maintained.

**Comment by satmandu** [comment]
(Also sorry for being so brusque in the initial comment. I'm sure you've had discussions about this already and have been thinking about ways to move forward if python 3 support becomes an issue.)

**Comment by Varstahl** [comment]
Oh, don't worry, no offence taken. I don't really follow Kodi's development actively, so I didn't know they wanted to push Python 3 (which I use all the time outside of Kodi). Thanks for the information and the suggestion.

Since this is broader than just MechanicalSoup I'll open a new specialised issue as to not flood you with notifications. Thanks for the heads up :)

**Comment by Varstahl** [comment]
You know what, fuck that noise and the "new" mechanize with binaries, I just crafted a module for MechanicalSoup to replace the buggy mess that is mechanize. Way to go.

**Comment by Sandmann79** [comment]
@Varstahl There is no need to this, i've already done it in the last days :wink:. Just want to do some tests.
In the next step i would switch to Beautifulsoup 4.

**Comment by Varstahl** [comment]
> @Varstahl There is no need to this, i've already done it in the last days

OUCH! I've got a (temporary) build with bs4 and mechanicalsoup, and several other python3 fixes and adjustments. I'm gonna push it in a branch in a few minutes, so you can merge in the MS change. I've also updated the addons requirements to bs4 and mechanical soup, so that too should be covered.

**Comment by Varstahl** [comment]
Also, I laughed when the new Mechanize that supports Python 3 has been pushed to the matrix branch of Kodi literally seconds after I reopened this thread :D

**Comment by Varstahl** [comment]
@Sandmann79 I just pushed my (messy) python3 changes to the [add-py3](https://github.com/Sandmann79/xbmc/tree/add-py3) branch. It's still a bit chaotic, I got stuck between BS4 and MechanicalSoup so I didn't manage to go further yet. I already changed some constructor calls to BS4, changed the imports and the addons.xml, haven't finished testing yet and since BS4 now uses the CSS selectors there's some rewriting to do. Once you merge in the mechanize change and the BS4 calls are completed, we should be mostly golden.
