### ISSUE TITLE
No video starts

### ISSUE THREAD

**Issue by IGonza** [Sandmann79/xbmc#227]
Latest libreElec on rpi3.
When I try to start any video, nothing happens.

https://pastebin.com/McSDP1yE

**Comment by Varstahl** [comment]
Something's very wrong with your installation/setup:
```
NOTICE: DecodeJpeg: unable to decode http://ecx.images-amazon.com/images/I/51qczwcD5VL.jpg 500x375
 ERROR: Open - error probing input format, https://d2lkq7nlcrdi7q.cloudfront.net/dm/2$RNTL3SZqURP3HK6rFdfySvact8o/6fa1/2964/c9e2/4622-8b90-fef62869b755/3f458ef1-cbf6-4292-a291-d0f3fafeac61_corrected.mpd
```
For unknown reasons your Kodi isn't able to read jpegs or mpds. Might be a connection issue, I don't know, but if it can't even read an image properly there's not much I can help you with.

Also, as you can see in the little snippet log you posted me, the addon actually did its job, it's IS.A that's unable to read the stream (although, again, if that setup can't read jpgs, something's _very_ wrong).

Since there's a lot of information missing, are you actually using a LibreElec build with Kodi 18?

**Comment by IGonza** [comment]
@Varstahl , thanks for your response.
it looks like simple restart has fixed the problem.
Yes, I use the latest 8.9.5.001 (which is beta) with kodi 18.
