### ISSUE TITLE
Release amazon vod 0.6.8 not show

### ISSUE THREAD

**Issue by CGarces** [Sandmann79/xbmc#267]
I'm using plugin.video.amazon-test 0.6.7

I not see 0.6.8 released yesterday.

Navigating from "install from repository" "Sandmann79 Repository" shows 0.6.7

See full log at
https://pastebin.com/EUctN2vs

**Comment by Varstahl** [comment]
Force an addon update via Kodi. Kodi caches the log, it usually can take up to 24/48 hours for it to realise there's an update, unless you manually force a check.

**Comment by CGarces** [comment]
How can I force the check?

**Comment by Varstahl** [comment]
I honestly don't really remember, it changed overtime. In Kodi 18 I think there should be an option somewhere in the addon manager. I only know of this because once I experienced the same problem after check on my other box if everything went fine, but the update didn't appear. I can tell you that 0.6.8 is up and fine, that I know because it shows on the update list.
