### ISSUE TITLE
Support H.265/VP9 instead of H.264

### ISSUE THREAD

**Issue by azmann75** [Sandmann79/xbmc#273]
Is Amazon VOD support VP9 codec? I always see video is using H.264 codec only. VP9 use less data bandwidth compare to H.264 at same resolution and better quality. I use netflix add-on, most new movie are encoded using vp9, thus use less bitrate, but better quality.

**Comment by Varstahl** [comment]
If Kodi supports it then yes, but the problem is that it's actually Amazon that decide who gets what, not the other way around. I would guess VP9 is used by Android, but I haven't reversed the Android apk so I'm not sure. Also, you're kind of mixing apples and oranges, we have ways to request H.265 instead of H.264, which is superior to VP9, but it's not currently supported by Kodi, at least in the version shipped with Amazon (at least judging by my tests).

**Comment by ghoshben** [comment]
probably recent kodi support H.265 (atleast on windows) and params['deviceVideoCodecOverride'] = 'H265' will return HEVC manifeast

**Comment by Varstahl** [comment]
Last I checked that didn't work, but I could test again shortly.

**Comment by Varstahl** [comment]
No, H.265 still doesn't work. Maybe in the future, I'll keep this open.

**Comment by pachulo** [comment]
Hi @Varstahl ! Is H.265 not yet supported by Kodi?
Thanks!

**Comment by Varstahl** [comment]
I've been out of the loop since late last year, covid and a child have put a serious wrench on my ability to work on this project, I'm unable to provide info atm. It might, it might not, I have no idea.

**Comment by Sandmann79** [comment]
@pachulo H265 is already supported by Kodi, but it seems to work only on Android L1 devices with Amazon. 
There's no chance to get it on Windows or Linux machines. 
I'll add an settings switch in the next release for easily testing.

@Varstahl bad to hear about, wish you and your family all the best and as always take the time you need.
