### ISSUE TITLE
Reduce overall loading times

### ISSUE THREAD

**Issue by santhoshnsscoe** [Sandmann79/xbmc#281]
When we go to a section e.g. Kids/Movies/TV Shows, it fetches all the videos under it and it is taking minimum 15 minutes to get all the videos.

If pagination is implemented, then this wait can removed and user can just click and go to next section.

**Comment by Varstahl** [comment]
The pagination hasn't been implemented for a number of reasons that require the entire section to be loaded. The first time you load any one section it will take an enormous amount of time, but everything gets cached and will subsequently reload in a way shorter time.

As things stand, I don't think pagination will be implemented as-is, and even admitting it will, it would still require the entire catalog to be fetched anyway.

**Comment by pierredefermat** [comment]
Hello. As a work-around, can we have a right-click menu item or a separate menu item, that does 'refresh list' which can work in the background? the users could do it, and once done can navigate the items without much lag.

**Comment by Varstahl** [comment]
That will come but I need a bit more time to work on it, it's a bit more complex than it seems. It will probably come in an update or two.

**Comment by Paco8** [comment]
I mostly use only the watchlist because the other sections take much to download.

In previous versions the addon downloaded only the list of episodes of the seasons I had in the watchlist, now it seems it downloads the list of episodes of all seasons even if they are not in the watchlist. While this may be good, it also increases a lot the download time, specially if there are shows in the watchlist with many seasons and many episodes.

The problem is that the cache gets corrupted sometimes, and now it takes longer to download the info about the watchlist. Before, I had to wait about two minutes to download the data of my watchlist, now I have to wait almost 10 minutes, so it's quite inconvenience.

I don't know, maybe the addon could make a backup of the cache from time to time, so if later the cache gets corrupted it could load the info from the backup instead of start over.

**Comment by santhoshnsscoe** [comment]
For me watchlist doesn't work at all. Anyway, i am only using search to get the videos and then see that. That seems to be faster and better.

**Comment by Varstahl** [comment]
As you all know there have been several changes needed to the core of the system, throughout the addon's lifespan. When I originally started developing the addon I had no clue about either the necessities of Kodi integration or the route the addon would be going over the years.

Yes, it's a bothering (I'm the first one to admit that), yes it should be improved, and yes it should not corrupt ever. I'm having a bit of a nightmare with python's mutability and non-mutability, selectively corrupting in case of errors, and at the moment I didn't find a viable solution.

**Comment by Varstahl** [comment]
Ok, on a second note, let's talk about it. I never experienced a cache corruption no matter how much I abused the addon over the years. What is your cause for video data corruption/catalog corruption that can't be fixed using the Refresh functionality?

**Comment by Paco8** [comment]
I actually didn't have cache corruptions when I used version 0.6.9. I experienced a few cache corruptions when using the latest ones. In my case it happens this way: I have several seasons from my watchlist added to the favourite section of kodi. Sometimes when I try to enter in a season, I can only see the blue circle spinning, but the list of episodes doesn't appear. After awhile I press the back button in my remote and then a popup message says the cache is corrupted.
Then I go back to addons, enter in the Amazon addon, watchlist and shows. Then I see in the popup that the addon is loading again the info about episodes. Howeven when it finishes sometimes I find that something is not right, like displaying an asin number instead of the season name. At this point I delete the two cache files, to start over.

**Comment by Varstahl** [comment]
0.7.0 was a bit of a curse for a number of changes to their backend. The first release had a typo, the second release came before a supplementary change of amazon's backend, third time's the charm. Also, to solve a number of problems, 0.7.0 has a new method for video endpoints, to stop same videos in different paths being treated as different. This is what will cause old things set in favourites to (probably) stop working.

I believe there will be another update possibly breaking the favourites/library soon-ish, but the video data should never be touched again. I've fixed and refined a lot of the processing, and with the refresh functionality being ironed out it should no longer be necessary. Catalog, maybe, at least for the moment, but not VideoData, which is the thing that takes most time scraping.

Another possible change, on top of the other things, would be to stop using python objects and pickle and opt for a SQL/DB based approach. This could have some RAM advantages, but I need to weight it.

Another real problem that I didn't have to face initially is Kodi's caching of objects. When I started developing the addon there was no possible corruption because in case of failure there was a "don't save changes" approach. On the subsequent run both catalog and videodata were reloaded from disk, so there was no corruption, ever. Since a few months ago the way the addon is loaded changed radically, caching drastically improved performances but now we have errors to deal with programmatically.

As for stuff taking "too much time", I agree, but it (should) be a one time bother. Suppose I put an automatic or manual option to automatically scrape everything primevideo.com has to offer, in exchange of a few hours worth of time. At that time, loading times across the entire catalog are severely decreased. Could anyone report failures after the 0.7.0-ter implementation? Aside the initial bother, did anyone have actual problems with the cached data since the last update?

An additional solution could be to instead reduce the number of data requests for episodes and movies. That would instantly load everything, except some metadata (thumbnails, runtime, and so on), that could be scraped in the background. It's quite inconvenient for movies, since I like to decide which movie to watch based on how much time I have available, but it could be made an option for primevideo users.

I'm open to suggestions, just remember that, to be on the same page:
* pagination as appears on primevideo.com will (probably) never come, since it's the most useless thing ever;
* delayed season scraping could be a thing, but I'll need some time to figure it out;
* obeying the addon option to "only show season instead of tv series" in the watchlist will be implemented.

**Comment by harikt** [comment]
Hi @Varstahl , 

I am not so familiar into the code base. But looking into I guess you are using sqlite to populate the db. One suggestion is how about we download the sqlite from the cloud which contain all the scraped data ?  The wishlist is different, but the rest of the sections are common. What do you think ?

* I am also in favour of running it in background after fetching 10-20 items. So we can display atleast the scraped contents.

**Comment by Paco8** [comment]
Not all content is available in all countries. Also the synopsis and so on are in different languages, so I don't know if it would be possible to use a common database.

For me, I think the best and probably the fastest, if it were possible, would be to use the primevideo api to get the info in json format. https://github.com/Sandmann79/xbmc/issues/279

**Comment by Varstahl** [comment]
> I am not so familiar into the code base. But looking into I guess you are using sqlite to populate the db

Not quite, in my particular section of code I don't use any DB at all, just python objects.

> One suggestion is how about we download the sqlite from the cloud which contain all the scraped data

There are at least half a dozen marketplaces, not to mention 16 different languages (at least). How do you pick and choose? Theoretically possible, but unrealistic.

> For me, I think the best and probably the fastest, if it were possible, would be to use the primevideo api to get the info in json format

@Paco8 it's nowhere near enough. A good chunk of the data is already parsed from JSON. The bottleneck _is not_ HTML parsing, the bottleneck is the sheer amount of single HTTP requests that must be performed to get basic info off Amazon's servers. I'll go on a limb and say, ok, I do that immediately and it optimistically saves us 10% of the time (which it doesn't, because there are now other problems, but let's pretend it does). At this point we saved 1 minute out of 10. There are still 8 minutes worth of loading from `GetPlaybackResources` API endpoints.

For the fucking sake of me, I can't understand why they removed multi-ASIN requests for GPR _only_ for primevideo.com endpoints. It's beyond me.

**Comment by harikt** [comment]
Hi @Varstahl ,

I noticed the search is too slow ( Sometimes takes more than 5 mins ). Can we have an option in the configuration to have a pagination based one ?

I am trying to find in code where the search and how things are working behind the hood. In case if you have some pointers please guide me. Else I will look into it myself.

**Comment by Varstahl** [comment]
https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/resources/lib/primevideo.py#L971

**Comment by santhoshnsscoe** [comment]
When we click on movies/kids/tv, then sub categories should come. We should not fetch all videos inside them. Once the sub categories are clicked, then only videos should be loaded.

For me it took more than 30 minutes and after that it stopped.

Fetching videos should be at last stage.

**Comment by Varstahl** [comment]
In fact that's exactly what happens. The only option is when there's a widow carousel, which has no "further click". Then there's nothing I can do there.

If amazon sucks don't put the blame on me.

**Comment by santhoshnsscoe** [comment]
I was just thinking after loading all the movies I get only sub folders to click further to view the list of videos. So it might be better to load the videos of these sub categories instead of loading all movies.

**Comment by Varstahl** [comment]
Widowed categories **don't have anything to load**:

![fc69500e-9b0c-4df9-9001-ac58fd8388d9](https://user-images.githubusercontent.com/284077/54545159-6552d380-49a1-11e9-98bb-66676bb78248.png)

Besides, again, the boostrap in some way, shape, or form, has to happen at some time.

**Comment by santhoshnsscoe** [comment]
Amazon is adding lots of movies to the list. Uninstall and remove all the cache and re-install amazon vod. When you click on Kids, it takes nearly 20 minutes and then we can see the Watch next kids, kids and family tv, etc. That is ok.

But, when we click on the movies, it takes more than 30 minutes and then it stops. If we click on movies once more, it load for 30 minutes more and then stops. Not able to navigate inside the movies section. I think, it is due to lots of movies added to amazon. Same for TV Shows section also. It was working one month before version.

So, nowadays I just search for the title and then watch the video. Not able to navigate to the Movies and TV Shows section.

**Comment by Varstahl** [comment]
Yeah, that sucks bad. While considering loading times, sometimes I forget I'm on a gigabit network. I can see how it just times out for huge lists, so what bothers me on a new installation on a gigabit network with sort of "close" server location can be a nightmare for some people.

Several structural changes need to happen, for the moment I'm thinking:
* change from python object to a DB, to increase resiliency and avoid corruptions.
* provide, as requested by some, an initial bootstrap that scans the entire catalog once. If started on the background service, there wouldn't be loading problems and data should never corrupt due to timeouts.
* possibly delay metadata scan. This depends on a lot of variables, including the change to API endpoints, so will need some testing.

I'll get working on it as soon as I can, after implementing an automatic and preferential language selection, that should also fix #271 and #287. Hope to find some free time to dedicate to the project in the next few days.

**Comment by Paco8** [comment]
I just don't get why the entire catalog has to be downloaded. Even if it's done in the background it will use bandwidth, and probably I'll never need most of the data.
Wouldn't it better to just get only the info that is required for that moment? For example, if I enter in the "comedy" section, it's only necessary to get the titles and the posters of those movies, not all the details. Then when I click on one of the movies, it would get the details for that particular movie. Why spend a lot of time downloading data for hundreds of movies when I'm just browsing and I only want to play a movie?

**Comment by Varstahl** [comment]
> Wouldn't it better to just get only the info that is required for that moment?

That's exactly what happens now.

> if I enter in the "comedy" section, it's only necessary to get the titles and the posters of those movies, not all the details. Then when I click on one of the movies, it would get the details for that particular movie.

When you click on a movie it can't get anything, it just plays the movie. The information must be there **before** it is shown. That's per Kodi standard. Also, if we're going API, we need to ask additional information anyway, otherwise we don't even have a proper thumbnail to begin with.

We have options, of course. We can decide we don't give a damn about actors, we don't give a damn about runtime, we don't give a damn about synopsis, we don't download that and we avoid multiple calls. But then is it useful? I've been trying to please everyone, but amazon kept giving less and less data to work with, which resulted in more and more calls, and more and more loading time.

> I just don't get why the entire catalog has to be downloaded. Even if it's done in the background it will use bandwidth, and probably I'll never need most of the data.

It's a tradeoff. Some people prefer not to waste time when they actually want to watch something in favour of wasting a bit of time after the first installation. Also, *a lot of people*, actually like and want amazon's entire catalog to be exported into Kodi's library, with a perfect integration.

Of course it will always be optional, but as far as I can see that's the only "remedy" I can see that makes the most people happy while making the least people unhappy. Basically, we're talking politics.

Another reason why some data parsing is needed is that, speaking for myself but I'm far from the only one, people like me **want** to know how long an episode/movie is, before actually starting to watch it. It's part of the choosing process. Some data, like runtime, can be approximated, but not everything and not for everything.

*Pick your poison*.

**Comment by Paco8** [comment]
Ok, I see. So the download of info about movies seems unavoidable, but maybe it would be possible to reduce the download time for TV shows. I mean, if there are 10 movies in a list, the addon has to download 10 html pages to get all the information, but if there are TV shows I think the addon right now downloads the information about all episodes of all seasons, so 10 TV shows would mean to download hundreds of html pages.

Maybe only the basic information should be downloaded. If there are 10 TV shows, download the 10 pages of those 10 TV shows, that's the sypnosis, poster and the list of episodes. When the user clicks on a TV show, then the addon will download the info about each episode.

**Comment by Varstahl** [comment]
> I mean, if there are 10 movies in a list, the addon has to download 10 html pages to get all the information, but if there are TV shows I think the addon right now downloads the information about all episodes of all seasons, so 10 TV shows would mean to download hundreds of html pages.

Actually no, depending on what you access, let's say a category, it doesn't load anything, with the exceptions listed shortly below. When "a bunch" of seasons get downloaded for whatever trigger, let's say 10 seasons, there are 10 HTML parsing with some information and 1 API call for each episode (JSON), _because Amazon disabled multi ASIN requests for primevideo.com_. On amazon.de you take a bunch of episodes, you bundle them together, you request 1 page and get _all the data you need_. PrimeVideo.com is the lesser child, so you have to make one request for every single episode.

I have to check whenever I can if there is anything usable to that extent with the new APIs introduced. That could reduce loading times something fierce, like 20 times faster. Up to the last time I checked, it wasn't supported.

> Maybe only the basic information should be downloaded. If there are 10 TV shows, download the 10 pages of those 10 TV shows, that's the sypnosis, poster and the list of episodes. When the user clicks on a TV show, then the addon will download the info about each episode.

It already does this, except when it can't. For example, the "keep watching", which is orphan, and watchlists. In every other case it doesn't download series and episode data. Episode data is loaded at the same time as season data, and season data is only loaded when the season is accessed. Except, as I said, with orphan carousels/scrollers.

---

A few notes.

My design, as explicated by the terms I used in the code, like "Lazy Loading" was to load as little information as possible. The bare minimum to have everything you need, and nothing more. Then they removed ASINs from the category pages, so we needed to scrape the page for the videos (movies were loading way faster in the first versions of the primevideo.com website). Then they removed synopsis and controls. Then _they even removed titles from the show lists_. This situation pisses me off as well, but unless I can find a way to reduce loading times without removing basic needs (titles and synopses are cool) the only changes I can do are of structural/integrity type.

I'm a regular user as well, so rest assured that if I find a way to download the entire primevideo catalog in 3 minutes instead of 3 hours, I'd be real happy. Until then I'm forced to "make do with what I have".

I'm also quite tempted to have some worker threads, so that instead of doing N requests on the same connection we could split the load amongst multiple connections, greatly reducing the load times.

**Comment by Paco8** [comment]
Would it be possible to figure out and use the same API that the primevideo apps use in Android?

**Comment by CGarces** [comment]
Hi @Varstahl 

Don't understand why if I go to "your watch list"->"TVShows" it download all the episodes of the TV Show
Can you explain the "orphan item" problem? 
Not is posible to fetch the data from https://www.primevideo.com/watchlist/ref=atv_nb_wtl  ?
I see some json data inside `<script src=""> `tag...
The episode information can be fetch  when I click in the folder of the specific TV Show...

**Comment by Varstahl** [comment]
> Would it be possible to figure out and use the same API that the primevideo apps use in Android?

I'm not sure. Sandmann79 was doing some tests with it, but then disappeared, I have no clue if they can be used or not. Also, I didn't reverse an APK, so I have no idea if it's much different from what we're using.

> Don't understand why if I go to "your watch list"->"TVShows" it download all the episodes of the TV Show
> Can you explain the "orphan item" problem?

Sure. There have been a few outages and breakages that made me change the way the series are downloaded, so I'll just break this down.

#### 1. Why does it download all the seasons

Due to Amazon being a bitch, I had to introduce pre-scraping because several seasons where removed from the listing. They don't need it, since the website/app allows you to pick the season, but we do because we don't have the privilege. So, in order to have working TV Show, whatever season comes first in whatever place (watchlist, catalog listing, etc.) we scan the entire TV Show to avoid going for example into a comedy series and seeing half the series listing. No refresh would help you there.

#### 2. The problem with orphans

As you can see in the [screens above](#issuecomment-473984733) some categories don't have the "Explore more" or whatever the link is called. When they do, I just put the category name and a lazy load to point the explore URL, and we delay everything.

When there isn't, depending on the flavour of the month, we reached the point where we just have the thumbnail, and no other information. So in case of movies we build the category name and place the movie information into it, with series we have multiple problems:

* we don't have the show name
* we don't have the show id
* we don't know the season numbers
* we don't have basic season information

So, to start, we need to dig into the season information. From there, and a subsequent API call to the endpoint, we extract the common show id to make sure everything makes sense when we display it (because of course amazon fucked up even that). So at this point we have a season, N calls for each episode, and relative show information gathered from the season page and from the API endpoint.

At this point we get in trouble. Since people access the same series from multiple places, if you have season 2 in the watchlist, and then go on a series page, depending on how amazon shows results, you will have season 1 or season 3 missing. Everything that can be taken from cache is taken (season 2), everything that is not listed by Amazon can't be retrieved (therefore no other season). So that is the reason why we go back to point 1 above and download all TV show information the first time we encounter a show of any kind.

#### 3. Can we delay season loading?

And idea that popped recently in regard to orphan categories, is that maybe it could be possible to cache the HTML/JSON data and lazy load from that data instead of a URL. With that we could be able to delay the loading of widow categories, but I'd need to potentially alter the codebase substantially to do that. Technically possible, though. Wouldn't work with the watchlist though, because when we reach the TV Show/Movies in the watchlist, everything is orphan, so we need to gather all the information.

**Comment by CGarces** [comment]
> Wouldn't work with the watchlist though, because when we reach the TV Show/Movies in the watchlist, everything is orphan, so we need to gather all the information

I don't get it, "orphan" is a list without "explore" link, but you can acess to the watchlist with the menu in the top corner....

**Comment by Varstahl** [comment]
Yeah, I expressed myself poorly. The watchlist abuses [this url](https://primevideo.com/watchlist), when you get into shows or whatever, it's already the end link, but contrary to what happens [here](https://www.primevideo.com/search/?queryToken=eyJ0eXBlIjoicXVlcnkiLCJuYXYiOnRydWUsInBpIjoiZGVmYXVsdCIsInNlYyI6ImNlbnRlciIsInN0eXBlIjoic2VhcmNoIiwicXJ5IjoicF9uX2VudGl0eV90eXBlPVRWIFNob3cmc2VhcmNoLWFsaWFzPWluc3RhbnQtdmlkZW8maW5kZXg9ZXUtYW1hem9uLXZpZGVvLWV1cm8mYWR1bHQtcHJvZHVjdD0wJmJxPShhbmQgc29ydDonZmVhdHVyZWQtcmFuaycgKGFuZCBzdHVkaW86J2FtYXpvbiBzdHVkaW9zJyAoYW5kIChub3QgKG9yIGF2X3ByaW1hcnlfZ2VucmU6J2NoaWxkcmVuJyBhdl9wcmltYXJ5X2dlbnJlOidmYW1pbHknKSkgKG5vdCAob3IgYXZfc2Vjb25kYXJ5X2dlbnJlOidjaGlsZHJlbicgYXZfc2Vjb25kYXJ5X2dlbnJlOidmYW1pbHknKSkpKSkmYXZfb2ZmZXJlZF9pbl90ZXJyaXRvcnk9SVQmcXMtYXZfcmVxdWVzdF90eXBlPTQmcXMtaXMtcHJpbWUtY3VzdG9tZXI9MiIsInJ0IjoiaGZ1VWtac2VlIiwidHh0IjoiUHJpbWUgT3JpZ2luYWwgZWQgZXNjbHVzaXZlIiwib2Zmc2V0IjowLCJzeXMiOlsiQ01TX1QxIl0sIm5wc2kiOjAsIm9yZXEiOiJOUVhYRzRGQ01BSlExSzRaNFZLRTowIiwic3RyaWQiOiIxOjEyVjNUTVgwOEZSQzdFIyNNWlFXR1pMVU1WU0VHWUxTTjUyWEdaTE0ifQ%3D%3D&pageId=default&queryPageType=browse&ie=UTF8) you have a lot of data missing from the listing. The only way to know what you're listing is to scan the season. Once you scan the season, you're scanning all the seasons and episodes.

**Comment by Paco8** [comment]
I'm afraid I still don't get why it's necessary to download the info of all episodes of all seasons of a show. I mean, even if a category only shows one season of a show, the html of that season contains the links to the other seasons. You can save those links and when the user clicks on one of those seasons, then download the information of the episodes.

**Comment by Varstahl** [comment]
You'd be correct if there was a single entry point. It worked like that before, so if you had season 3 in the watchlist, you go to the catalog and the other seasons never appear. I **had** to introduce the forced season scraping to avoid problems users were having when browsing the PrimeVideo catalog, having widespread missing content.

**Comment by CGarces** [comment]
> You'd be correct if there was a single entry point.

@Varstahl I understand the problem, you need all the season data of one TV shows but...
Why all this data is fetch when I go to "your watch list"->"TVShows"  and not just when I go to "your watch list"->"TVShows" ->"TV Show folder" ?

**Comment by Varstahl** [comment]
Because there was no data to populate basic information for a series when listed in the watchlist. With the new API endpoints we can maybe now skip that process. I still had no time to investigate, will try take a look asap.

**Comment by CGarces** [comment]
> Because there was no data to populate basic information for a series when listed in the watchlist.

Are you sure? the json data at https://www.primevideo.com/watchlist/all/ref=atv_wtlp_all?page=1&sort=DATE_ADDED_DESC is not enough? what is missing?

**Comment by Varstahl** [comment]
Now? And for someone? Probably. But honest to God, there have been and there are so many different freakin' revisions live at the same time, I'm not sure if the JSON data is the same, let alone for anyone.

**BUT** we have the Watchlist API endpoint now. I just need more time.
