### ISSUE TITLE
pausing a video

### ISSUE THREAD

**Issue by thk12** [Sandmann79/xbmc#338]
hello there :)

i'm using a fresh install of OSMC on a raspi3 (=kodi 18.3) i've installed a clean version of amazon VOD and it works very well. But when i "pause" the playback, the screen starts to flicker, like TV loose the hdmi signal here and there..

i'am the only one with this behavior? 
greetings

**Comment by Varstahl** [comment]
The playback is not handled by the addon, the addon merely fetches the url and gives it to Kodi. If the video starts playing, from that moment it's up to Kodi and InputStream.Adaptive.

With that being said I'm not aware of this being a problem, in general. There is currently a switch from Leia to the new builds of Matrix (Kodi 19), so depending on what you're using it might help to check if there's specific problems with your build.

Also, from the reports of other users, a lot of times LibreElec is a better alternative to OSMC in terms of fixes and compatibility.

Since I don't own a raspberry of any kind I can't give you more detailed information.

**Comment by thk12** [comment]
thanks mate, guess i give libreELEC a try. btw: wheres the donate button for this project?

**Comment by Varstahl** [comment]
There's no donations, we're (mainly) a couple devs sharing our work pro bono, with a few more helping us here and there. The closest thing if you're a PrimeVideo.com user would be the donation button on my twitch.tv page, but that's about it :D
