### ISSUE TITLE
UserAgent list can't be retrieved/updated

### ISSUE THREAD

**Issue by Sandmann79** [Sandmann79/xbmc#340]
The [source site](https://techblog.willshouse.com/2012/01/03/most-common-user-agents/) for the UserAgent list added recently a Cloudflare DNS protection, which makes it impossible for the addon to retrieve it.
There are a [solution](https://github.com/Anorov/cloudflare-scrape) for python outside, But i think it's easier to switch to another site, like https://developers.whatismybrowser.com/useragents/explore/operating_system_name/windows/.

**Comment by Varstahl** [comment]
TFW you might have underestimated the number of hits going to their website so much so that they added a bot protection to reduce the strain…

Jokes aside, tbh I was never a big fan of this solution. We could use multiple sources to interpolate and cache a list of user agents and provide it through some of my servers instead of bothering other people's servers, as I have enough unused monthly terabytes of data to go around. I could probably complete this alongside the release-based kodi repository I'm working on.

**Comment by Sandmann79** [comment]
Sounds good, that makes us less dependent from other sites. Let's do it so.
