### ISSUE TITLE
Command line to update cache

### ISSUE THREAD

**Issue by Bouhmarc** [Sandmann79/xbmc#344]
Hi, 

I run this plugin on a raspberry pi 3 (OSMC distribution).
I don't use Amazon prime very often so every time i want to use it, it takes a very long time to get all the categories/series/movies/...

I was wondering if there is some kind of command line i can use in a cron in order to update on regularly basis...

If not, maybe this could be an interesting enhancement..

Regards

Marc

**Comment by Varstahl** [comment]
Are you a primevideo.com user? If so, what version are you running?

**Comment by Bouhmarc** [comment]
Hi
I'm not sure to understand your question..

I own a prime account..
Here are all the "versions" i can think of..
OSMC based on Kodi 18.4 (compile on 2019-11-01
Amazon VOD : 0.7.4
Amazon VOD Language : French
If this is not the answer to your question, could you be more specific?

Thx !

Marc

Le mer. 6 nov. 2019 à 21:20, Bruno Passeri <notifications@github.com> a
écrit :

**Comment by Varstahl** [comment]
It's ok. There is a new version with significant cache performance improvements (orders of magnitude faster). It's not into the master yet, so I'll keep this open for the moment.

If you want to test the development branch, you can [follow these easy steps](https://github.com/Sandmann79/xbmc/issues/343#issuecomment-549246720) and see if the problem is mitigated.

**Comment by Bouhmarc** [comment]
Great !
Do you have any idea of the release date of this new version ?

Maybe I’ll give a shot with the development branch this week end !
Thx for all !

Marc

**Comment by Varstahl** [comment]
Not quite, we're getting closer but there are a few things left to iron out and test yet. There's some big changes coming due to Kodi Matrix switching to Python 3.

**Comment by Varstahl** [comment]
If you want to update and test the new speeds, the latest version has been pushed to the public last night. Looking forward to your feedback.

**Comment by Bouhmarc** [comment]
Hi there,

Juste updated the plugin but i've got another problem..
I can't log in anymore

When i try to log in, i've got a confirmation box in which i need to type
my password again and a captcha code.
When i validate this window, i wait a few seconds (4-5 s max) and then i
got the same confirmation window...
so i can't log in and test the speed !

Regards

Le sam. 16 nov. 2019 à 13:29, Bruno Passeri <notifications@github.com> a
écrit :

**Comment by Varstahl** [comment]
Hmm… do you get some error, or does it just pop back up again? Be mindful of the fact there might be spaces in the Captcha, you've got to write them down too, or so I'm told. If it still doesn't work, upload the log file on pastebin or somewhere similar, so that I may take a look into it. If you enable debug logging, you should also see a different file named "avod-login" or "amazon-login" in the userdata directory, we might need that as well. Just be mindful of the fact there might still be traces of your user/pass in the log files, I'm uncertain if we remembered to clear those up in the current release, so you might want to check and clear those out from the files you upload.

**Comment by Bouhmarc** [comment]
It just pops up again and again.
I’ll try with the spaces.. 

Marc

**Comment by Bouhmarc** [comment]
Hi
With the spaces in the captcha, it worked.. (this is weird, this is the
first captcha i see with significant spaces inside...)
concerning the performances, It seems to be faster, approximately 8-10
seconds to parse one page (the i see the notification..), i don't know if
this  is the time you're used to have.
I thought didn't have time to test much further, i'm on business trip by
now, so i don't have much time.

As soon as i can test correctly, i come back to you.

Regards

Marc

**Comment by Dada2201** [comment]
Hello @Varstahl as you mentionned it in #364 
Is this "fetching" manually cache is developped ?

Many thanks
