### ISSUE TITLE
Episode thumbnails are only shown in the WideList view

### ISSUE THREAD

**Issue by Paco8** [Sandmann79/xbmc#361]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version 0.7.9~beta

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: PC
- OS Version: Windows 10
- Kodi Version: 18.4

**Describe the bug**
The thumbnails in the episode listing are only shown when using the WideList view. All other views show the season poster for all episodes instead of the episode thumbnails.

**Comment by Varstahl** [comment]
I looked into it. Technically it's not a bug, that's exactly what amazon gives us. I don't think straight up replacing images is the correct thing to do either.

Adding an option to prefer thumbnails to poster images might be the most sensible thing to do.

**Comment by Paco8** [comment]
Well, in the previous version (0.7.5) the episode thumbnails were shown in those other views, so it looked like a regression,

**Comment by Varstahl** [comment]
It's the absolute same in 0.7.5. Prior to 0.7.5 there was no packshot grabbed, so I never noticed the problem.

https://github.com/Sandmann79/xbmc/blob/9814caafa4697fd4c16ae8717f89cc22a5064815/plugin.video.amazon-test/resources/lib/primevideo.py#L881

Given the "this is what Amazon returns" I've got to figure out what to do next. As I said, probably the best course of action is to set up a specific primevideo option to dynamically replace posters with thumbnails or to suppress posters altogether for episodes, since it would be silly to replace valid info with incorrect one.
