### ISSUE TITLE
howto: last watched content?

### ISSUE THREAD

**Issue by thk12** [Sandmann79/xbmc#363]
I am looking for a good way to get easily to the last watched content, for example when I start a new TV show. How do you guys do this?

Is it maybe possible to get an option to add new started series to the watchlist (as some kind of dialogue window)? This would greatly increase the WAF :-D -> https://en.wikipedia.org/wiki/Wife_acceptance_factor

**Comment by Varstahl** [comment]
Technically Amazon does that for you. You can find the "Keep watching" category in the menù (wording depends on the locale) that has the latest X watched TV shows, so you can bounce in there and keep watching from where you left off.

**Comment by thk12** [comment]
ah okay, really? there is no such menu. I am using amazon VOD and what i've got in main menu is only:

Watchlist
Movies
TV Shows
Amazon Channels
Search
Library

And even in TV Shows there is no item like "Keep watching".

**Comment by Varstahl** [comment]
The listing's geo localized so ymmv, but for example if I jump into "TV Shows" this is the first thing I see on primevideo.com:

![Keep watching](https://user-images.githubusercontent.com/284077/69245771-c3c2f800-0ba7-11ea-909c-a4446a321553.jpg)

Which includes the last season of "The man in the high castle" I started watching last night. And, in Kodi:

![kw1](https://user-images.githubusercontent.com/284077/69246040-40ee6d00-0ba8-11ea-82ec-ab311a45180d.jpg)
![kw2](https://user-images.githubusercontent.com/284077/69246044-41870380-0ba8-11ea-8bf0-239db0c92e76.jpg)

The same thing applies to movies. A lot depends on the local service they're providing, but this is generally the way they're doing it, which is why I didn't implement something similar myself. Which might come at a later date, I have a couple ideas, but for the moment I didn't find the need to.

Of course I think that category doesn't show up unless you specifically watched something. I'm not sure after how many series/movies it shows.

**Comment by thk12** [comment]
ah okay, i've checked this again with my german account and there is no such a item in amazon VOD but when i do a login into chrome, the "recently watched" items appear. 

Is there maybe a setting that prevent this function in AVOD?

**Comment by Varstahl** [comment]
Ah, sorry, it's possible that it just doesn't work for TLDs. I mistakenly assumed it was about primevideo.com, but I don't know how things go in the german side of things, since amazon uses two very different platforms.

**Comment by thk12** [comment]
ah okay, i didn't know there might be a difference between primevideo.com and amazon.TLD accounts

**Comment by Varstahl** [comment]
Yeah, they're two completely separate infrastructures, developed by different people. We're using the same base to provide similar functionalities to everyone, but there's still some differences here and there.

**Comment by thk12** [comment]
alright, thanks for clarification :-) issue can be closed then or maybe seen as an improvement

**Comment by Sandmann79** [comment]
Just for clarification. The implementation done with https://github.com/Sandmann79/xbmc/commit/7d1a66eb25821f22b8650bfa01f060745053919a is just on addon site. It doesn't sync the recently watched content directly with Amazon, but the addon sends the playback progress to Amazon. That means, if you use only the addon for playback, the watched items should similar. If you use another device or browser, than not.
