### ISSUE TITLE
Loading the list of movies and series

### ISSUE THREAD

**Issue by Wombidou** [Sandmann79/xbmc#364]
Hello,

First, congratulations for this work!

I have a question about how the addon works:
When I want to list the movies for example, the loading is very long because it loads all the pages:
Loading page 1
Loading page 2
Loading page 3
...
Loading page 17
And finally display all the movies.

Is it possible to use the following operation:
Loading page 1
Showing movies
Click on next page
Loading page 2
Showing movies
...

Maybe this option is already available but I have not found it.

I'm using Kodi 18.5 on Freebox Mini 4k and Amazon VOD 0.7.8.

Thank you

**Comment by Varstahl** [comment]
The first time around the loading takes a lot of time because some information are hidden behind different calls, so in order to process a category, especially for TV series, it takes a whole lot of time. On subsequent calls, since most of the data is already stored, it will only take a handful of seconds though, on my end about 10 seconds for 22 pages and about ~440 results.

There is an enhancement planned to 100% respect primevideo.com's pagination, it didn't make the cut for this release though.

But, again, after the data is cached, you will see a dramatic speed increase.

**Comment by Wombidou** [comment]
Thanks for your reply.

**Comment by harshgandhi** [comment]
Is there a way to manually cache every list entry? User can start to load all pages overnight so there's little wait time during actual use.

**Comment by Varstahl** [comment]
Not yet, see #344. It's planned, though.
