### ISSUE TITLE
Yo, can i somehow increase the buffer size for the playback?

### ISSUE THREAD

**Issue by MparkG** [Sandmann79/xbmc#392]
... it appears as the buffer doesnt get filled quickly enough, such that the playback stops regularly and then is either stuck or takes a few seconds to restart.

its no bandwidth problem...

Thanks

**Comment by Varstahl** [comment]
The addon doesn't manage the streams other than setting up and providing data for Kodi and IS.A. Your problem is either due to CDN, bandwidth, network congestion or decoding power. So, here's some workarounds:

1. try to enforce a lower bandwidth in IS.A
2. make sure you enable audio/video passthrough in Kodi
3. try to force a specific CDN in the addon settings
4. make sure your network isn't congested and if possible using algorithms such as [Cake](https://www.bufferbloat.net/projects/codel/wiki/Cake/)
5. make sure your hardware is able to playback such videos (for example RPi have trouble with Widevine encrypted addons for anything higher than 720p, sometimes less on certain models)
