### ISSUE TITLE
Blank rusults for some section

### ISSUE THREAD

**Issue by azumukupoe** [Sandmann79/xbmc#397]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version 0.8.1

**Prime Video Account (select one)**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Desktop PC
- OS Version: Windows 10 Pro
- Kodi Version 18.5

**Upload Logs**
[kodi.log](https://github.com/Sandmann79/xbmc/files/4074768/kodi.log)

**Describe the bug**
Some sections return a blank result after changing "Items Per Page" from default in the add-on setting.

**Comment by Sandmann79** [comment]
This is partially fixed with d16fdda96dc7361e817e6f045536e3b27424a330. 
But a few movies can't displayed with the API, which this part of addon uses. If one of this movies is in the list amazon's server returns an empty result.
Maybe this can be fixed by using another devicetypeid, but i didn't found it yet.
