### ISSUE TITLE
Can't access the sign in page

### ISSUE THREAD

**Issue by Magikreaper** [Sandmann79/xbmc#415]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)

**Prime Video Account (select one)**
- [x] primevideo.com

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 4
- OS Version: Raspbian buster with desktop 4.19
- Kodi Version :18.5

**Upload Logs**
N/A

**Describe the bug**
Via the addon parameters, I click on "sign in" then the loading never ends. No errors just the infinite loading.

**Comment by Varstahl** [comment]
Enable [debug logs](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi) and provide both kodi.log and avod* logs.

**Comment by abconnor** [comment]
Confirm that. Log:
ERROR: [Amazon VOD] Error reason: HTTPSConnectionPool(host='na.api.amazonvideo.com', port=443): Max retries exceeded with url: /cdp/usage/v2/GetAppStartupConfig?deviceTypeID=A28RQHJKHM2A2W&deviceID=d6fd6cc9a2e59264028161632e05d610f7da96f806e414436a03f9f9&firmware=1&version=1&format=json (Caused by SSLError(SSLError(1, u'[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:727)'),)) (SSLError)

**Comment by Varstahl** [comment]
Yep, debian enforces TLS1.2+, na.api.amazonvideo.com supports TLS1.0 only. [See this comment](https://github.com/Sandmann79/xbmc/issues/326#issuecomment-546262203) for more information.

**Comment by Magikreaper** [comment]
Ok thanks for the infos!
