### ISSUE TITLE
Some movies do not have sound

### ISSUE THREAD

**Issue by ntilagoa** [Sandmann79/xbmc#43]
Hello
I try the plugin and is working ok on Kodi 18 nightly except that some movies do not have sound.

**Comment by circharles** [comment]
Great addon! Thank you so much for your time and energy making it work. Your contributions to my entertainment options are appreciated. 

Same issue here. Nightly build of kodi 18 on raspberry pi3. Able to access movies and shows. Many shows play with sound perfectly. Some newer shows have video but no sound. Example: Red Oaks tv show plays with sound for preview and season sneak peak, but full length episodes have no sounds. Tv show "Goliath" plays video only for BOTH the preview and full length episodes. 

Google search reveals that folks with similar problem with unmodufied roku boxes identified problem as incompatibility between source sound Dolbysurround and devices' ability stereo. Not sure if this is the issue here or not.

**Comment by Sandmann79** [comment]
This bug is caused by the dd+ workaround, which the addon uses. 
This workaround modifies the stream url to get additional dd+ audio tracks (by default, we only get stereo audio).
In old versions, the addon uses an modifier, where allmost all tracks appear. But on a few videos, there where unplayable dd+ tracks included, which kodi played by default. The current modifier is taken from an TV device, so we should get only playable audio tracks with this one. But in your case, there are no audio tracks available, so i have to look at an different modifier.

In the meantime you can easily use the old modifier by replacing line 1137 in default.py:
`        mpd = re.sub('/[^/]*~/', '/2$cRlBqQh9nnSAW9qpcQWMwOQi3bA~/', mpd)`
with this:
`        mpd = re.sub(r'~', '', mpd)`
To check the audio track you should enable "Switch Audiotrack, if not valid" at settings -> general.

**Comment by circharles** [comment]
This worked. Thank you for the old modifier instructions. I can now play all titles with video and audio on raspberry pi 3b

**Comment by Sandmann79** [comment]
Thx for feedback.
Fixed for now with 7929dbd9f979a117be183dd41369ed3b34b96e79
