### ISSUE TITLE
Details on the Addon Disclaimer message? 

### ISSUE THREAD

**Issue by steffenWi** [Sandmann79/xbmc#45]
So, this question came up over here: https://github.com/asciidisco/plugin.video.netflix/issues/211. 

What parts of this plug-in could be in a grey-area/illegal? Or is it just a 'just in case' message?

**Comment by Sandmann79** [comment]
Like you wrote it is just an in case message. I didn't know any law in every country. So it's possible that to use this addon is somewhere illegal.

**Comment by Wheemer** [comment]
We live in an a backwards world when we are questioning the legality of a service we are paying for. It should be assumed that since we pay legally for the service, how and when we access it should be irrelevant. Surely the fact that it is not recording or downloading is the key to keeping it ok. I really love this plugin but wish it supported more countries like Canada

**Comment by Varstahl** [comment]
Closing this as the relevant information are now inside the [FAQ](https://github.com/Sandmann79/xbmc/wiki/FAQ#disclaimer-message-in-the-addons).
