### ISSUE TITLE
No audio when using S/PDIF

### ISSUE THREAD

**Issue by Micro-Crackedto** [Sandmann79/xbmc#455]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [0.8.3]

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [e.g. RPi] RPi 3B+
- OS Version: [e.g. Windows 10] LibreELEC 9.2.1
- Kodi Version [e.g. 18.4] 18.6

**Upload Logs**
https://www53.zippyshare.com/v/NGLbHq09/file.html

**Describe the bug**
No sound on any VOD content.
It works when I use HDMI, but I want to use my S/PDIF interface.
When watching a movie using HDMI, switching back to S/PDIF fixes it while watching.
I think it has something to do with the HDCP, but I'm not sure.
HDCP was enabled by default on IPA, and switching did not help.
It furthermore, also tells me there no audio streams.

**Comment by Micro-Crackedto** [comment]
UPDATE: It works on S/PDIF when toggling Language>Audio descriptions on, but I obviously need my S/PDIF to get 5.1 to work.

**Comment by Varstahl** [comment]
I don't want to state the obvious, but that's beyond the scope of the addon. As long as the video starts playback, we can't help you further, that's between you, the OS & Kodi.

With that being said though, are you sure that your 5.1 setup supports DolbyDigital+? Last time I had to setup for DTS it was a nightmare. Also, what happens if you pre-emptively set up Kodi to use the S/PDIF interface from Player > Audio, and then start movie playback?

**Comment by Micro-Crackedto** [comment]
It seems to be working fine now.
The weird thing is, I disabled support for DD, and it worked but no voice from center speaker.
I then turned DD back on and relaunched the movie and I get the correct 5.1 now.

I did notice that it sometimes does not start with any Audio Streams, but restarting the movie fixes that.
Seems like that's a bug of some sorts for me, but at least I got a workaround :)

**Comment by Varstahl** [comment]
Ok, *that* sounds like a problem with network speed/MPD proxy. If you don't need audio streams (and you don't since you're going 5.1, and you don't need some peculiar languages, you might try disabling the MPD proxy alteration for better results. If the problem is a timeout on MPD download, that will fix it.

If, on the other hand, is a problem on some CDNs (it does that at times), simply restarting the stream works most of the times.
