### ISSUE TITLE
Always asking for authenticator code

### ISSUE THREAD

**Issue by DasBiest** [Sandmann79/xbmc#47]
If two factor auth is enabled, you can't do anything without trying in your two factor OTP. Possible fix: Adapt the logibn method from the android tv app or "check"  the box on never ask for this device.

**Comment by Sandmann79** [comment]
You should disable the setting "Store Credentials instead of using the Cookie?" with 2FA enabled. After that you get never asked for this code. 

The login from Android TVs is already included in the auth_token branch. But in this case i get only an token from the response. This one is locked to the devicetype id used at pairing the device. The problem here is, that the devicetype id, which the addon uses for playback, didn't work at this login method and with other ids the playback fails.

**Comment by Sandmann79** [comment]
Fixed with 6599374219b2f8bc60d0d732d89d19bac33f7e50

**Comment by DasBiest** [comment]
Thanks!
