### ISSUE TITLE
Audio language only Original language

### ISSUE THREAD

**Issue by StyleHack** [Sandmann79/xbmc#486]
**Addon used**

* [x]  Amazon VOD (plugin.video.amazon-test)
* [ ]  Browser Launcher (plugin.program.browser.launcher)
* [ ]  Addon Version [0.8.6]

**Prime Video Account (select one)**

* [ ]  primevideo.com
* [x]  amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**

* Hardware: [Intel NUC]
* OS Version: [Windows 10]
* Kodi Version [18.7]

**Describe the bug**
Audio language of all Movies and Series in Original language. i can't set german audio. On my Smart TV it works fine, but not on kodi plugin. i've changed MPD disabled and add `"lc-main-av": "de_DE"` in C:\Users\<USERNAME>\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.amazon-test\config\accounts.lst. but nothing work.
Kodi Audio is German, Kodi System is German? what am I doing wrong?

**Comment by Sandmann79** [comment]
You're really set German as preferred audio language at kodi settings? 
You're watching through VPN or proxy?
There are different audio languages selectable at audio settings while watching a video?

**Comment by StyleHack** [comment]
Yes I have set the audio language to German:  Settings > Player > Language > Preferred language > German.  Is this wrong?

I am not using vpn or proxy.



That's exactly the problem, I only have e.g. English 1, English 2 there.  But not the selection German.



As I said, on my Smart TV I always have about 10 different languages.  But not in the Kodi addon.

**Comment by Sandmann79** [comment]
Strange I heard about this issue on primevideo but never on amazon tlds.
Audio Descriptions at language settings are disabled? 

Can you provide a debug log?

**Comment by Varstahl** [comment]
Well, in PrimeVideo cases it's a bug due to Kodi/IS.A (which should be fixed now, btw). Basically they get up to N audio streams, then sort them alphabetically, so "Deutsch" is almost always the first or close to the first, while other languages like "Italian" or "Norwegian" sometimes don't make the cut. This is absolutely weird though.

Can you find a video that has no German on Kodi, play it and check the audio streams it has?

![image](https://user-images.githubusercontent.com/284077/88456883-f5e8d000-ce81-11ea-90fd-3a1d1fd99bb5.png)
![image](https://user-images.githubusercontent.com/284077/88456886-fd0fde00-ce81-11ea-9884-f3ae050cd203.png)

**Comment by Varstahl** [comment]
Closing this as it's been long fixed in IS.A
