### ISSUE TITLE
Login Error after change of Amazon password

### ISSUE THREAD

**Issue by noexperiance** [Sandmann79/xbmc#493]
Addon used
 Amazon VOD (plugin.video.amazon-test) V0.86

Account type
 primevideo.com

System Setup (please provide the following information):
Hardware: Desktop X86
OS version: LibreElec
Kodi version number: Leia
%%%%%%%%%%%%%%%%%%%%%

I changed my Amazon password. 

When I wanted to change login information in Amazon VOD 0.86 I could not login anymore.  

Problem is: Amazon send an email in which I am asked to confirm that new login. 

Doing this from a browser window on kodi Chrome does work. It fails when I try to confirm my login from within the addon. 

Is there a possibilty to force the addon to save my login information? Since thats the way it works in a browser.

I guess, this issue could affect more poeple that just me.

PS: I enabled detailed logging and could provide avod-login.log
PPS: avod-login.log can be opend as html in a browser. It shows the same message I get when using a browser for login to Amazon.

**Comment by Sandmann79** [comment]
> PPS: avod-login.log can be opend as html in a browser. It shows the same message I get when using a browser for login to Amazon.
Please provide this file, it's very useful here.

**Comment by noexperiance** [comment]
Okay, so here is the file (I changed my personal information / my mail adress)
%%%%%%%%%%%%%%%%%%%%%%%
[avod-login.log](https://github.com/Sandmann79/xbmc/files/5018292/avod-login.log)

**Comment by TxBase** [comment]
I think, Amazon add some kind of "transaction-approval". Normaly the browser is waiting until the approval or the timeout occur.
Does the "virtual browser" process java script?

I vote for higher priority, since with broken login no user, which don't allready have an auth-cookie, can use this addon.

**Comment by Varstahl** [comment]
> I vote for higher priority, since with broken login no user, which don't allready have an auth-cookie, can use this addon.

We usually take login problems very seriously and try to solve them fast, the problem is that the login *is* working, and there isn't just *a* platform. I always clear credentials and log back in again through Kodi and the most updated addon version, and it always work.

It's counter intuitive for some, but figuring out *why* one of Amazon's endpoints in country X with whatever option Y on the account is non  conforming to the rest of the world at any given time is not very simple.

Lastly, with all of the above staying true, we're volunteering our time to the project, but in these trying times having sparing hours for project maintenance has been hard.

**Comment by TxBase** [comment]
I'm retry the login and now I can confirm, that it's success. This time I get the first time a dialoge about the confirmation.
But it's strange. This time I don't get a Mail in time and don't get android app notification. As I manually open the app I only get the window about the success confirmation. (I don't know if it was an old one) After it, I confirm the dialog and get a dialoge asking the confirmation code. Since there was no Mail at this time, I abort the dialog. Then I retry and just logged in.
In the past tries I confirmed the login many times, but the login process fails with a error dialoge before the mail and the app notification could be delivered. I don't know what happend, but I hope, this description is a bit useful.

**Comment by Varstahl** [comment]
> I don't know what happend

When it comes to amazon's servers, "welcome to the club" :D

**Comment by stephankurzawe** [comment]
Hi Guys,
I got the same behavior as @noexperiance. But it was the first time trying to use your app.
To be sure I tried my amazon account and the account of my friend as well. Both are showing the same behavior. Kodi returns with an unkown error. And the avod-login.log shows the amazon "waiting for approval"-page. We received SMS to conform the login, but this didn't help to login after approving the security alert. Let me know, if you need any more information.
[avod-login.log](https://github.com/Sandmann79/xbmc/files/5076869/avod-login.log)

**Comment by Sandmann79** [comment]
That's like @TxBase already mentioned. The Mechanicalsoup Addon, which is responsible for the login process, can't handle Javascript pages. So we have to look for an other solution.

As workaround you could enable two factor authentication at account settings on Amazon Website, login within the Addon (don't use App-Push it also uses a JS-Page) and disable 2fa, if you not need it anymore.

**Comment by noexperiance** [comment]
Thank you @Sandmann79 !
Your workaround does work for me. 
Nevertheless, the issue itself is still active.

Thank you for your support.

**Comment by abandonedze** [comment]
I had same problem. But i created new amazon account, payment option, and after that i loged without problem.
