### ISSUE TITLE
Option to configure catalog cache expiration time

### ISSUE THREAD

**Issue by satyadeepk** [Sandmann79/xbmc#499]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.8.8

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

### Feature request
Currently the catalog cache expiration is hardcoded to 11 hours. It will be great to have an option to increase or decrease this in the settings. This will be especially useful for large catalogs where pagination takes a long time.

https://github.com/Sandmann79/xbmc/blob/ce9f1b79355db0a38779b1850b0ad04826169801/plugin.video.amazon-test/resources/lib/primevideo.py#L287

I have some background in Python but new to Kodi and will be glad to contribute this if you can guide me on the relevant changes.

**Comment by Varstahl** [comment]
The catalog expiration time was always supposed to be temporary, and for the most part could also be redundant. A few modifications are needed to make the scraping faster, but if you want to help with with the cache timing you can create an option in the `settings.xml` under the `PrimeVideo` options, possibly an enum
https://github.com/Sandmann79/xbmc/blob/ce9f1b79355db0a38779b1850b0ad04826169801/plugin.video.amazon-test/resources/settings.xml#L107-L116
You can then add the option name to the bottom of the `Settings .__getattr__()`
https://github.com/Sandmann79/xbmc/blob/ce9f1b79355db0a38779b1850b0ad04826169801/plugin.video.amazon-test/resources/lib/common.py#L194-L201
The string in the elif block will be the string referred below as optionStringName, while the string in `self._gs('optionName')` is the name as specified in the settings.xml. They can be the same, but it's not mandatory.

After that, you can replace the hardcoded 39600 with the value configured in the options, and should become something like this
```py
self._catalog['expiration'] = self._s.optionStringName + int(time.time())
```
In any case, since I introduced the Refresh functionality, it would even make sense to insert a huge value, to just never delete cache. There are cleaner ways to do this last thing, but for the moment it should do.

Let me know if I can help further.

**Comment by satyadeepk** [comment]
Thanks for the detailed explanation, it's really helpful.

I am thinking of putting these options in the enum with default as 12 hours:
```
<setting id="catalog_cache_expiry" type="enum" values="1 hour|6 hours|12 hours|1 day|3 days|7 days|15 days|30 days" label="30257" default="2"/>
```
And then I will map these strings to integer seconds in common.py `__getattr__` function

Please let me know if these options sound good, or if you want to add or remove any option.
