### ISSUE TITLE
Linux Mint 20 Cinnamon vs Amazon VOD [Kodi 18.6]

### ISSUE THREAD

**Issue by kodi-rc** [Sandmann79/xbmc#518]
**Addon used**
- [ x] Amazon VOD (plugin.video.amazon-test))

- Addon version: 0.89+matrix.1

**Account type**
- [ x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:
- OS version: Linux Mint 20 Cinnamon x64
- Kodi version number: 18.6

**Upload Logs**

The dependency on xbmc.python version 3.0.0 could not be satisfied.

**Describe the bug**
Linux mint has two versions of Python, version 2 is called via the "python" command. Version 3 is called by the command "python3"

example:
$ python --version
Python 2.7.18

$ python3 --version
Python 3.8.5

When I try to install the Amazon VOD add-on on Kodi 18.6 with Linux Mint 20 Cinnamon, the following error appears:

The dependency on xbmc.python version 3.0.0 could not be satisfied.

**Comment by Varstahl** [comment]
Local versions have no influence over Kodi embedded pythong compiler. You mistakenly downloaded the repository for Kodi Matrix (19+, Python 3 only) instead of the Kodi Leia repo (18, Python 2).

Remove the repository, install the [correct one](https://github.com/Sandmann79/xbmc/releases/download/Repository/repository.sandmann79.plugins-1.0.3-leia.zip), the problem will be gone.
