### ISSUE TITLE
Amazon VOD: Does not store user preferred audio stream setting

### ISSUE THREAD

**Issue by tuxedo0801** [Sandmann79/xbmc#521]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 
All versions, also latest

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Wetek Play 2
- OS version: CoreElec, latest
- Kodi version number: latest

**Upload Logs**

**Describe the bug**

My box is connected via optical cable to my AV receiver. It's not the newest, so it is not capable of decoding DD+.
Many amazon stream come with DD+ and the plugin always takes the DD+ stream, no matter how often I manually switch to AAC stream and save this as my preferred setting.

So either this is a bug, or I am doing something wrong.

**Comment by Varstahl** [comment]
Audio and video tracks are picked by Kodi, not the addon. Regardless if you want to disable DD+ you can enable Audio descriptions in the addon's settings.

![image](https://user-images.githubusercontent.com/284077/99645058-033c5280-2a4f-11eb-9f48-174ed317b33e.png)

That has the side effect of disabling surround, so it should work in your case.

**Comment by tuxedo0801** [comment]
@Varstahl 
Thanks, that solved my problem, althugh I do not understand what kind of audio descriptions I now have enabled and why this does disable DD+ etc. 
In KODi itself, I have configured which codecs etc. my system can handle. But the addon seems to ignore this and requires this "workaround"?

**Comment by Varstahl** [comment]
The addon does pretty much nothing in terms of playback/codecs, other than tell Kodi where to find audio and video tracks (all of them). I don't know of any way to setup Kodi to prefer stereo tracks, and at the moment we can't hide tracks from Kodi, so that it only sees a certain track rather than all of them.

The fact that we can disable DD+ is a byproduct of a feature for the visually impaired. You will find that now there will be a few more stereo tracks, where supported, which have audio descriptions of the movie, although it should never be selected by default, so no big deal there either.
