### ISSUE TITLE
Only one TV show season displayed when more are available

### ISSUE THREAD

**Issue by skycamel** [Sandmann79/xbmc#535]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.0

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: RPI 3B+
- OS version: LE 9.2.6
- Kodi version number: 18.9 Leila

**Describe the bug**
Not really a bug, more an enhancement I guess.
When using "Top Tv shows" (or other category) and select a certain Tv show, let's say Psych, then it will only show one season, not all available seasons. Same when you add to your watchlist, only one season is added.
When using the browser (on my PC) I can click on the show and will then be able to select the season I want to watch.
Would that be possible in AmazonVOD?
Thanks,
Luc

**Comment by Varstahl** [comment]
Hmm, that's strange. I don't recall what I did but generally even in Watchlist there should be all the seasons, and not just one. I'd tell you to just "hit refresh" in the contextual menù but I remember that something went wrong with it so that's a bug to fix too.

I'll look into this, but no ETA, recently I've been overburdened.

**Comment by skycamel** [comment]
I'm not really sure what you mean by "refresh", don't have that in my context menu.
As far as series goes, I even don't have a clue how I can navigate to the next season?
Now I have to say, I wish you a lot of strength and courage LOL.
If I see what a mess Primevideo makes in it apps! My smart tv is different from my smartphone and again different from my web browser on my PC. I don't know how on earth you can all figure that out
Cheers

**Comment by Varstahl** [comment]
Yeah, I go on fueled by hatred alone. At one point before doing something "smart", I had to keep 6 different versions of the same code at once, because stuff would break at random places in the world. Now it's mostly small maintenance, except when things break majorly.

Back to the topic at hand: if you right-click or press the contextual menù key on a remote, you will find a bunch of options, such as "add to favourites", "play from here", and the like. For some PrimeVideo folders and all TV Series and Seasons, there's also one additional menù item called "Refresh". I think there's a bug somewhere though atm or some regression broken by an update by Amazon, so I'm not sure if that works in your case.

Not all folders can refresh though. If on the PrimeVideo website a category has an external link, then it can be refreshed, if it's widowed, as in the case of banners, then it can't be refreshed.

**Comment by skycamel** [comment]
Well sorry, I looked at all possible context menu's and nowhere I can find "refresh" (unless you mean update to Library?)
This whole Amazon way of doing things is really messed up.
So, when I go in Tv Shows / All Shows (in AmazonVOD) then when I click on the thumbnail of one of the shows I will get the underlying Seasons, that's ok. Now when you go to Tv Shows/ All Shows and right click on the show and in the context menu you "Add Show To watch list" then when going to Watchlist and click on the show then you only get season 1 (or first available) and it's not possible to select season 2, etc..So it doesn't show a selection of the underlying seasons, only the episodes of season one.
Now, that's somewhat similar to the website, however when clicking on the show it will give the episodes of season 1 but on the left top you can select the season.
Also, depending on how you navigate to shows (like search, Top rated, etc..) it will then display the show per season, so not the complete show plus underlying seasons(?!?) That's both in the website and AmazonVOD
Cheers,
Luc
PS Is there another place we can continue this discussion as I don't think maybe doing it here is appropriate?

**Comment by Varstahl** [comment]
Uhm, wait, there is no "add to watch list" for PrimeVideo. Are you from DE/JP/UK/US?

**Comment by skycamel** [comment]
Nope, I have an NL account and living in Belgium and on the web I'm using primevideo.com. (we don't have amazon.be but we're legally using the amazon.nl)
My Region in settings is "Auto"

**Comment by Varstahl** [comment]
This is super confusing, can you post a full log with debug mode enabled please? You can find more info on how to do it in the wiki at the top.

**Comment by skycamel** [comment]
Attached the kodi log. Let me know if you need more
Here I went into the AmazonVOD, Tvshows / All Shows and then "add show to watch list"
[kodi.old.log](https://github.com/Sandmann79/xbmc/files/5904561/kodi.old.log)

**Comment by skycamel** [comment]
You got me thinking. I do in fact use SmartDns, but no vpn. And in SmartDns Mazon prime is set to US.
My router is setup to go to the smartdns DNS server so all connected devices would you that.
However, my Kodi RPI is configured with 8.8.8.8 as DNS server so smartdns should have no impact.
I will try your suggestion to see if that makes a difference.
Now, would it be possible to have two logon's?
BTW how do I download network.py? Copy the whole text and past it in a file I create?

**Comment by skycamel** [comment]
I'm so, so sorry. You were right, I just renewed the login process and now I'm getting the same menu structure as you posted.
And yes now I have the "refresh" in the context menu
I updated the network.py (no more captcha right? Great!)
Please accept my apologies, I really didn't intend to waste your time, it was an oversight on my part.
Cheers,
Luc

**Comment by Varstahl** [comment]
> Now, would it be possible to have two logon's?

it is, AVOD supports multi users, it's in the opt-in in the options.

> I just renewed the login process and now I'm getting the same menu structure as you posted

No probs, glad you got it working, have fun watching :)
