### ISSUE TITLE
script.module.win_inet_pton not available

### ISSUE THREAD

**Issue by tefracky** [Sandmann79/xbmc#549]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.0

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 3
- OS version: LibreELEC 9.2.6
- Kodi version number: 18.7

**Upload Logs**

**Describe the bug**

I am using Kodi 18.7 on LibreELEC on a Raspberry Pi 3. Both is completely new installed and nothing changed. When I want to install the Amazon addon, there is a missing dependency, which cannot be installed: script.module.win_inet_pton (not available). Therefore, also Amazon cannot be used. How can I fix this?

**Comment by Sandmann79** [comment]
The addon is available via the official Kodi repo:
http://mirrors.kodi.tv/addons/leia/script.module.win_inet_pton/

**Comment by numetaler** [comment]
i found this problem as well, and i also downloaded this plugin, but i don't understand how to install it in Libreelec. if i try to install it from zip file it says that its not in the right format

**Comment by Sandmann79** [comment]
The solution posted above doesn't work in LE, because win_inet_pton is only for windows client. That's the reason, why these addon is not available or installable.

You can try to install the addon, which depends on win_inet_pton, manually (just check the logs) or ask in LE Forum.
You should also update to the most recent version of LE/Kodi 18.9.

The Amazon addon didn't have win_inet_pton as dependency. 
So i can't help you here anymore.
