### ISSUE TITLE
No FHD for TV Series on Windows

### ISSUE THREAD

**Issue by nonobio** [Sandmann79/xbmc#566]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: PC
- OS version: Windows 7
- Kodi version number: 18.9

**Upload Logs**

[https://paste.kodi.tv/evosulanok.kodi](https://paste.kodi.tv/evosulanok.kodi
)
**Describe the bug**

Hi,

Thanks for this great add-on.

If I'm right: FHD isn't available for movies but should be available for TV series ?

If yes, maybe I have an issue because my TV series are played at  960x540 resolution.

Thanks.

**Comment by Sandmann79** [comment]
See here: https://github.com/Sandmann79/xbmc/wiki/FAQ#how-can-i-play-movies-in-hduhd

**Comment by nonobio** [comment]
I already read this FAQ but it says "movies" and I found these messages :

[https://github.com/Sandmann79/xbmc/issues/255#issuecomment-461001562](https://github.com/Sandmann79/xbmc/issues/255#issuecomment-461001562
)

[https://github.com/Sandmann79/xbmc/issues/255#issuecomment-466814765](https://github.com/Sandmann79/xbmc/issues/255#issuecomment-466814765)

So think the limitation was only for movies. But so, it is also for TV Series. Ok.

Thanks

**Comment by Varstahl** [comment]
You're correct, initially it was only for movies, but they later reduced the ability for TV series as well. The wiki hasn't been updated in a while.

**Comment by nonobio** [comment]
Thanks for the precision. Any chance to have FHD for movies and/or series in the future?

**Comment by Varstahl** [comment]
It depends on a number of factors, primarily the device. On some devices, mostly android based, it works, on PC not so much. It's more of a technical problem with the Kodi+IS.A stack.

I know there are possible solutions being worked on, but I'm not allowed to say more. It's possible, but it's not really anything us addon developers can do on our own. Our addon *does* support them, but if you can't playback due to DRM, our hands are tied.

**Comment by nonobio** [comment]
Thanks for your reply. Bye

**Comment by Sandmann79** [comment]
> I already read this FAQ but it says "movies" and I found these messages :

Forget to change this, now it's done.

**Comment by kannabianka** [comment]
I'm sorry to try and tell something about this issue which is more than clearly closed.
But i have one thought: when I look at Primevideo through a browser I think I'm getting the video at least in 720p (there's the HD "light" turned on.

Is it possible, by tweaking some parameter, to get the video stream from a browser and the audio stream from the plugin having 720p + 5.1?

Right now I'm using an old PS3 to do this job...

**Comment by Varstahl** [comment]
Not technically, unless you start the browser, start the audio in Kodi, and start playback of the muted video at "supposedly" the same time. If anything happens, everything will desync. Due to the nature of the DRM, we can't do anything about it yet, until Kodi tools or part of it get certified by Google. Which, again, is a lengthy process, if possible at all.

**Comment by kannabianka** [comment]
Thank you very much for the quick reply!
