### ISSUE TITLE
"One or more items failed to play" error

### ISSUE THREAD

**Issue by mholl1983** [Sandmann79/xbmc#569]
**Addon used**
- [x ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 
0.9.4

**Account type**
- [x ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Beelink GT1 Standard
- OS version: Android 7.1.2 (Alvatech Custom Rom)
- Kodi version number: 19.1

**Upload Logs**

https://drive.google.com/file/d/1-50Hbv85Ncj0Ztu6wQ1N3CTvNuQyu01r/view?usp=drivesdk

**Describe the bug**

After a fresh install and signing into my Prime account, I see the movies/TV shows populate as expected.

Any entries that are not included with Prime throw the correct error "content not paid for" or something like that.

Any entries that ARE included with Prime and I've been able to run fine on the Android Prime Video app just don't work. They either load indefinitely or silently fail and throw the error "one or more items failed to play". I hope the logs provide a clue and I'm happy to provide any more details that'll help.

**Comment by Varstahl** [comment]
```
ERROR <general>: AddOnLog: inputstream.adaptive: Unable to find license;hdcpEnforcementResolutionPixels in JSON string
ERROR <general>: AddOnLog: inputstream.adaptive: Initialize failed (SingleSampleDecrypter)
```

There's a problem with the Widevine DRM decipher/decryption. Try using the [native android apps](https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon-test#android) for playback. This allows you to browse content using Kodi and then just watching using the native apps instead of InputStream.Adaptive.

**Comment by mholl1983** [comment]
Thanks for your reply. Maybe a dumb question, but is there any advantage to this set up over just using the Prime Video app for everything?

**Comment by Varstahl** [comment]
Convenience, for most. You can use Kodi for different things and use the addon for catalog generation so you can start playback for most resources from the same place. PrimeVideo diverges from Netflix in which the DRM restrictions are much, much tighter, so unless something changes in the Kodi/IS.A ecosystem it's unlikely to support the same features as the native app, which is why we support it under android.

If you like how the PrimeVideo app works, and you don't have other uses for Kodi, then you can go for it straight, there are no other advantages to using the addon.

I, for one, started working on a Kodi addon because I really didn't like how the native/browser app managed things, although it got better over time.

**Comment by mholl1983** [comment]
Gotcha and makes sense. Thanks for providing your feedback! I was considering the plugin for a steadier resolution during playback. I don't have a Widevine L1 device, so don't expect full HD, but the Android app seems to fluctuate the quality, even with a steady internet connection.

**Comment by mholl1983** [comment]
If your plugin provides even a steadier SD stream than the app, I'd be happy. :)

**Comment by mholl1983** [comment]
Actually, even when I set the add on to use the Android app for playback, I get the same error.

**Comment by Varstahl** [comment]
Well, it *should* work to begin with, not at the highest quality, but the fact that even the app doesn't work leaves me puzzled. You might try one thing in InputStream.Addon settings, there should (could?) be a setting called "HDCP Override". You can try turning it on and see if the playback starts. Under android you shouldn't have any issues with that, and it *might* fix the HDCP license issue you're facing.

I've been out of development for a few months, so I'm not even sure if the option is still there in Kodi 19.1, but taking a look won't hurt I guess.

**Comment by mholl1983** [comment]
HDCP override did the trick; thanks again!
