### ISSUE TITLE
No playback and Infinte caching of pages

### ISSUE THREAD

**Issue by stefcep** [Sandmann79/xbmc#573]
I applied the latest addon update that was supposed to fix the infinite caching of pages, but whilst there is "progress" its still not right.

1. I can open a folder that only has video titles inside and I can see the titles and banner and information of title When I try to playback the title, the screen freezes and no way out of that screen unless I power down.
2.  If I open a folder eg "Included with Prime" that has folders nested inside it, opening one of those folders starts the infinite page caching.

System: Australian Amazon Prime Librelec 9.95.5 Generic X86_64 Kodi Matrix, Inputsream adaptive widevine.cdm, over-ride HDCP is off/on no difference

**Comment by jswetzen** [comment]
I’m having the exact same issues, and I installed just a week ago, so I should have that fix you mentioned.

Swedish Amazon prime, RPi 4, OSMC Kodi Matrix, InputStream

**Comment by Sandmann79** [comment]
The infinity caching can be fixed by enabling paginating at addon settings primevideo tab.
If this not help, you can try the current [beta 3](https://github.com/Sandmann79/xbmc/files/8101641/plugin.video.amazon-test-0.9.5_beta3.zip). 

The playback problems are currently widevine related. 
You have to downgrade the widevine library to an older version. 
This may help for OSMC:
https://discourse.osmc.tv/t/how-to-get-libwidevine-working-in-osmc-kodi-18-19-netflix-disney/90848

**Comment by jswetzen** [comment]
Amazing. You answer was really quick and sport on. Thank you sir, my Amazon
prime time is saved!

lör 19 feb. 2022 kl. 15:03 skrev Sandmann79 ***@***.***>:
