### ISSUE TITLE
Subtitle download error

### ISSUE THREAD

**Issue by yotzo001** [Sandmann79/xbmc#576]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: v0.9.4+matrix.1

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Amlogic S905x3
- OS version: Coreelec 19.2-Matrix_rc3 
- Kodi version number: 19.1 

**Upload Logs**
[Pastebin link to log](https://paste.kodi.tv/avularahiw)

**Describe the bug**

Hi,

When downloading subtitle from opensubtitles (to any other source) .srr gets downloaded in /storage/.kodi/userdata/addon_data/service.subtitles.opensubtitles/temp/ but cannot be copied to right place. I tried to set a custom subtitle folder instead of "Next to the video" under Settings/Player/Language to /storage/downloads/ but it didn't help.

It is related to matrix and Amazon VOD somehow, because
-on the same hardware with Amazon VOD and Kodi 18.5 it worked flawlessly
-subtitle downloading works with locally stored files (example included in the log)
-subtitle downloading works with another streaming provider (N*flix, not included in the log)

I hope it will help you find the problem.

Thank you for your hard work!

**Comment by frodo19** [comment]
Yes I can confirm. I tryed with Win7 kodi 19.4 , and Firestick 4K max Kodi19.4 , both come with same error. 
Subtitle download not possible with this addon.  :(

**Comment by GasmoN** [comment]
Hi, I can confirm this for ANY kodi 19 and 20 version and build. It doesn't matter which subtitle plugin I am using, subtitles can't be downloaded. And since we are almost at KODI 20 release, which brings a lot of new features and improvements, I just wanted to ask are there any plans for fixing this issue to work at least on kodi 19? I am asking that because I tested kodi 20, and majority of plugins built for kodi 19 works on kodi 20 too.
