### ISSUE TITLE
Add support for Microsoft Edge please.

### ISSUE THREAD

**Issue by tooelitepete** [Sandmann79/xbmc#587]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- [x] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:
- OS version:
- Kodi version number:

**Upload Logs**

**Describe the bug**

It still uses Internet Explorer as an option. It needs support for the latest Microsoft Edge.
And if possible, seeing as Xbox uses Microsoft Edge Chromium as the default web browser, can we add the option to launch the Xbox Edge Browser when using Kodi on Xbox?

**Comment by Sandmann79** [comment]
MS Edge is a System App without a real executable file to start, because of that it isn't possible to add it as a predefined browser.
But you can use the Script setting as described [here](https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon-test#commandscriptbatch) for it. 
The following command line should work: 
`explorer.exe shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge {u}`.

Alternativly you can use [MicrosoftEdgeLauncher](https://github.com/MicrosoftEdge/edge-launcher/releases/tag/1.2.0.0) to start Edge.
