### ISSUE TITLE
Add-on: Amazon.it?

### ISSUE THREAD

**Issue by pi4630** [Sandmann79/xbmc#59]
Hi,

thanks for the nice work on the amazon add-on.
Why doesn't it work on amazon.it - i.e. why the limitation?

Thanks
#pi4630

**Comment by acca** [comment]
Suppose this is same as #22

**Comment by Varstahl** [comment]
It's indeed the same issue

@pi4630 the problems were born with the global launch of Amazon Prime Video, with a dedicated platform (primevideo.com) instead of the local amazon shop pages (amazon.com, amazon.co.uk, amazon.de, amazon.jp). Sandmann can't access and test the primevideo.com because afaik he's based in germany, and it requires a working amazon prime account outside of USA/UK/DE/JP to sort the matter out.

I'm currently working on it though.
