### ISSUE TITLE
Add-on 'script.module.mechanicalsoup' is not compatible with Kodi

### ISSUE THREAD

**Issue by marcogaio** [Sandmann79/xbmc#592]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Vero 4K+
- OS version: -
- Kodi version number: 19

**Upload Logs**
2021-10-26 22:57:21.033 T:11556   ERROR <general>: Add-on 'script.module.mechanicalsoup' is not compatible with Kodi
2021-10-26 22:57:21.034 T:11556   ERROR <general>: CAddonInstallJob[plugin.video.amazon-test]: La dipendenza da xbmc.python versione 2.25.0 potrebbe non essere soddisfatta.

**Describe the bug**
Plugin does not install; i'm using the 'matrix' version.

**Comment by marcogaio** [comment]
I can go to Settings -> Browser addon -> install from repository -> Sandmann79s Repository Matrix -> Addon video -> Amazon VOD.

Then here i can choose between 'Versions', 'Install' and 'Dependencies'.

In 'Dependencies' i have only 'InputStream Helper', minimal 0.4.4+matrix1, installed 0.5.8+matriz1.

If i choose 'Install' error about MechanicalSoup popups.

**Comment by Varstahl** [comment]
Oof, yeah, Kodi doesn't show script modules in the interface. I don't remember if you can install it from a zip though, you might try grabbing it directly from [here](https://github.com/Sandmann79/xbmc/tree/master/packages-py3/script.module.mechanicalsoup).

The other alternative, given that you have the Matrix repo installed and no faulty dependency, is a package conflict with other repositories. You may try to disable them one at a time (or all at once, except for Sandmann79) and try to install the addon again.

Note that with the repositories disabled, the only way I found to re-enable it was to use addon > search, since it doesn't show them in a convenient place (at least on my build, but then again my build is outdated, they might've fixed this already).

**Comment by DavidEnergie** [comment]
> I can go to Settings -> Browser addon -> install from repository -> Sandmann79s Repository Matrix -> Addon video -> Amazon VOD.
> 
> Then here i can choose between 'Versions', 'Install' and 'Dependencies'.
> 
> In 'Dependencies' i have only 'InputStream Helper', minimal 0.4.4+matrix1, installed 0.5.8+matriz1.
> 
> If i choose 'Install' error about MechanicalSoup popups.

Same for me...

I disabled all other Video, Music, PVR and Game AddOns, reinstalled the Sandmann repository and the Amazon VOD AddOn, nothing changed. 

 (I forgot to mention, I use a RPi 3, not Vero4K)

**Comment by Varstahl** [comment]
> I disabled all other Video, Music, PVR and Game AddOn

Disabling addons doesn't work if it's a repo conflict. You might try uploading the [full log](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi) to see if we can catch what the issue is. I know for a fact that some piracy related repos broke installations in several cases, and if that's the case you're on your own, but other than that as demonstrated several times over the years, it's a local problem to your installations.

**Comment by DavidEnergie** [comment]
Thanks @Varstahl!

Here the full log:
https://paste.osmc.tv/ofujalayeb

No piracy repos here.

Also, it might be helpful info that I had a major upgrade (no clean-reinstall) to Matrix recently. I might have uninstalled some libraries that have shown "deprecated or "disabled" after that, before installing Netflix (castagnaIT) and trying Amazon VOD.

**Comment by Varstahl** [comment]
```
INFO <general>: CAddonMgr::FindAddons: script.module.mechanicalsoup v1.0.0 installed
INFO <general>: CAddonMgr::FindAddons: script.module.myconnpy v8.0.18+matrix.1 installed
```
There. I know I can sound like a broken record, and some people even think I don't read what you write, but as I said, this is the proof: you have a MechanicalSoup installed for Kodi Leia 18. See how the very next module has `+matrix.1`?

Now, assuming you don't know where that comes out of, if you have access to ssh, you can find where that folder is and remove it. Should be on `~/.kodi/addons/script.module.mechanicalsoup` or `/storage/.kodi/addons/script.module.mechanicalsoup`, or somewhere like that. Remove it, and then install the addon again, and it should work.

**Comment by DavidEnergie** [comment]
Thanks for your patience. I am still learning the kodi specificities.
As suggested, I removed the mechanical soup addon by
`rm -r ~/.kodi/addons/mechanicalsoup*`
Rebooted and tried to reinstall Amazon VOD. It didn't work as it didn't install the new version, for some reason ("mechanicalsoup version 0.12.0+matrix.1 could not be satisfied").

I then realized I had missed to remove all orphaned addons (after update to matrix) as suggested here: [Sandmann matrix upgrade issue](https://github.com/Sandmann79/xbmc/issues/557).
After doing this I installed the mechanicalsoup as well as the pyautogui addon by downloading the zip-files, moving them onto my Kodi and installing through:
settings>addon browser>install from zip.

Now the Amazon VOD works.

I suggest though, to try removing the orphaned addons in kodi before removing mechanicalsoup manually. Couldn't test maybe this could work as well.

**Comment by marcogaio** [comment]
> I then realized I had missed to remove all orphaned addons (after update to matrix) as suggested here: [Sandmann matrix upgrade issue](https://github.com/Sandmann79/xbmc/issues/557). After doing this I installed the mechanicalsoup as well as the pyautogui addon by downloading the zip-files, moving them onto my Kodi and installing through: settings>addon browser>install from zip.

I can confirm that, after removing __orphaned__ addons, i was able to install the Amazon plugin.

Thanks to all!

**Comment by Varstahl** [comment]
Np, glad it works :)
