### ISSUE TITLE
 Many new movies/seasons are missing

### ISSUE THREAD

**Issue by 1023660** [Sandmann79/xbmc#607]
Hi,

I have this issue for quite some time now: The watchlist is only displaying half, maybe less, of the added films. If I add new ones, some end up being displayed, some don't. It is not a matter of alphabetical order, it seems like random if they are displayed or not. I do not geht an error message. I haven't found similar behavior in a websearch. Does anyone have a clue?

Raspberry Pi 3+
Kodi 18.9
Libreelec 9.2.8

Thank you and kind regards,

Stefan

**Comment by Sandmann79** [comment]
The problem here is the old API that the addon uses. This has been trimmed more and more by Amazon over the last years and currently returns incomplete or no results at all. 
Amazon also discontinued support for devices that would have used the API years ago.

But you can switch to the current beta 3, taken from the web_api_tld branch:
[plugin.video.amazon-test-0.9.5_beta3.zip](https://github.com/Sandmann79/xbmc/files/8064291/plugin.video.amazon-test-0.9.5_beta3.zip)

With this you can enable the Web-Api at addon settings Amazon TLD tab and get the content listed like on Amazon's web page.
