### ISSUE TITLE
Missing episodes in series when using web_api

### ISSUE THREAD

**Issue by DDuck007** [Sandmann79/xbmc#609]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: compiled web_api_tld from this  repo @30.01.2022

**Account type**
- [ ] primevideo.com
- [X] amazon.de

**System Setup (please provide the following information):**
- Hardware: RPi4
- OS version: Libreelec 10.0.1
- Kodi version number: 19.3

**Describe the bug**
When using "web_api" some episodes in a series are missing, e.g. opening "Thunderbirds are go" in "normal" mode shows 26 episodes both in series 1 and series 2. Switching to "web_api" only 25 episodes per series are shown.

**Comment by Sandmann79** [comment]
There was a bug at initial video scan, it has been fixed with commit 3b53a0ed779541c6f269ebf2c9faecb7c1abaed4 and included in [beta 3](https://github.com/Sandmann79/xbmc/files/8066417/plugin.video.amazon-test-0.9.5_beta3.zip).

Since the series is already cached, it must be updated via the context menu to display all episodes.

**Comment by DDuck007** [comment]
just tested - looks good - Thank you!
