### ISSUE TITLE
Possible HD stream solution?

### ISSUE THREAD

**Issue by t0mtee** [Sandmann79/xbmc#627]
I think that a combination of using a browser and an extension such as [Cast Kodi](https://github.com/regseb/castkodi) to open the video on the browser and stream it to Kodi would theoretically solve the HD issue. I have tried using Cast Kodi with Prime Video, and it doesn't work at the minute, but it might work with some tinkering. This solution would allow for HD+ playback on Kodi with all the benefits Kodi has but will only work on PC.

**Comment by ThreeDeeJay** [comment]
Did you ever get this working? or any other way to get HD playback, for that matter 👀

**Comment by OsoaGH** [comment]
> Did you ever get this working? or any other way to get HD playback, for that matter 👀

I don't personally have the skills to make this, and I haven't heard anything from the addon authors about this since I made the issue, so I'm assuming this isn't in the works

**Comment by ThreeDeeJay** [comment]
> YouTube, Twitch, Vimeo, SoundCloud ainsi que Acast, Ace Stream, Apple Podcasts, Ausha, Bigo Live, BitChute, Blog Talk Radio, Castbox, Dailymotion, DevTube, Facebook, Flickr, Instagram, ItemFix, Jamendo, Mastodon, Megaphone, Mixcloud, Odysee, Overcast, PeerTube, Podcast Addict, podCloud, Pokémon TV, Radio, Reddit, Rumble, Steam, Streamable, TikTok, Ultimedia, Uqload, Veoh, VideoPress, VideosHub, Vidyard, Viously, Vudeo ; 

seems like [Amazon Video isn't supported by Cast Kodi](https://github.com/regseb/castkodi#description), so I doubt it's the way to go. It would need to implement support but at that point we'd be reinventing the wheel since we have the VOD addon.

> HD and FHD video quality are only available on hardware supported devices (Android devices/FireTV/Firesticks). To enable reproduction of such videos you need to enable Override HDCP status in IS.A settings, or use a different playback method

This seems a bit ambiguous. I'm not sure if there's a hard lock for amazon devices or if we can get HD on windows using that option (just tested it and it doesn't help but I also wonder if there's something I'm missing)

**Comment by Varstahl** [comment]
> This seems a bit ambiguous. I'm not sure if there's a hard lock for amazon devices or if we can get HD on windows using that option (just tested it and it doesn't help but I also wonder if there's something I'm missing)

Compared to Netflix and other services, which don't use this level of encryption, Prime Video locks 720p+ behind Widevine and "safe path", which means the Google verifies the binaries and says that they are "secure"/"tamper proof". For example browser get certified. If Kodi was to have such a certification, it could play FHD without issues, but it doesn't.

Technically speaking, if Cast Kodi leverages a browser, then it *should* work with PrimeVideo, since by using Vivaldi/Chrome/Brave/Opera/Edge there is the secure path verification for the binary chain, therefore it would provide the needed keys for the stream decryption.

Haven't used any of those, didn't have time to check, and I'm still late for even older tasks (bought a Firestick to test integration and possible solutions for the API/FHD/H265 and whatnot, plugged it in just once and collecting the dust ever since).

**Comment by ThreeDeeJay** [comment]
Interesting. any ideas if there are plans to get Kodi certified?
also just tested Cast Kodi and to my surprise it did launch a stream, so maybe there's hope?. *However* it just plays the trailer/teaser, and still low res (Undetermined, h264, 720x360 769020 bps video and AAC stereo track.)
I know I can just use the browser for HD but I'd also like to enable surround sound tracks and have easier navigation when I'm using the TV.

**Comment by ThreeDeeJay** [comment]
@Varstahl you know what would be a reasonable compromise in the meantime?
an addon that syncs browser and kodi playback. Cast Kodi already has access to the seek position so an addon like it could sync the prime video website playback
I've done it manually before so I can mute the browser to get surround sound from Kodi, and just switch to the browser for HD video.
Not gonna lie, kinda wasteful on bandwidth but for me it's hard to choose between HD video and surround sound, if available. 😅

**Comment by regseb** [comment]
The new version _7.8.0_ of [Cast Kodi](https://github.com/regseb/castkodi) (require [Chrome](https://chromewebstore.google.com/detail/cast-kodi/gojlijimdlgjlliggedhakpefimkedmb) 124+ or [Firefox](https://addons.mozilla.org/addon/castkodi/) 125+) supports Prime Video thanks to Amazon VOD. For your HD problem, I don't think Cast Kodi can help as it only sends the video ID (e.g. `plugin://plugin.video.amazon-test/?mode=PlayVideo&asin=amzn1.dv.gti.ff3e6df2-2fa6-4a7c-bab3-43972be660cb&name=Heirate%20Meinen%20Mann%20S1`).
