### ISSUE TITLE
What happens when you try to play a video that’s not available on Prime.

### ISSUE THREAD

**Issue by theEpicjosh** [Sandmann79/xbmc#645]
I have a prime account and I love using the Amazon VOD app to watch my Prime videos. However, I do have a question.

I was searching up a movie that wasn’t available on Prime such as “The Hobbit”. As I write this, it’s only available to either buy or rent. What happens when I press play? 

Does it show up an error/payment screen? 
Does it play the film and automatically charge me without my knowledge (if so, would it buy or rent the film)?
Or does it play the film without charging me (probably would be illegal)?

Anyway, I love the Amazon VOD add-on, I just want to know what happens before I make a choice. Thank you understanding!

**Comment by weisenhan** [comment]
>What happens when I press play?

You get an error stating: Unable to play. Product not purchased.

**Comment by Varstahl** [comment]
Depends on the platform you're using it from Amazon DE/JP/UK/US should ask you if you want to buy or rent, for every other country it might either fail or ask you to pay. There is no auto pay.

Also, sorry for the delay, I thought I already replied and only now I realised I had the comment unsent here for the past 3 days.

**Comment by knappster1** [comment]
My experience in the US with the web api enabled (Kodi 19.4 and prime addon 0.9.5) is that there is a Kodi notification that it hasn't been purchased.  There is no prompt to rent/buy.  I like that purchasing is not allowed within Kodi.

With the old API it was easier to identify which videos were included with prime because the ones not included were listed in a different (orange?) color.  This is with Kodi 19.4 and addon 0.9.5
