### ISSUE TITLE
login with cookie impossible on arm devices

### ISSUE THREAD

**Issue by kartracer54** [Sandmann79/xbmc#78]
hi new to this world.. just got a pi3 and am trying to get it going for amazon. i have it up and running but get a amazon VOD error upon logging in to my account. i can then see movies and tv shows but when i try to play one it then gives me a unable to play, browser or script not found. check settings. then it goes into a never ending load. this is the last log file in the folder. not sure if this is how to handle things so guidance would be much appreciated
[log-2018-02-03-01.02.56.zip](https://github.com/Sandmann79/xbmc/files/1691251/log-2018-02-03-01.02.56.zip)

**Comment by Sandmann79** [comment]
The login error is a common error on ARM platforms, it depends on the cookie library wich is used currently. It will be fixed in the upcoming version 0.5.0, meanwhile you can enable the option "Store credentials instead using cookie" at addon settings > Connection.
Then you should choose "Inputstream" as playback method, this is the only one, wich was working on RPi's, but currently there are some problems. Check Issue #62 for more information.

**Comment by kartracer54** [comment]
thanks that fixed the login issue and the input stream error. now i can see all of my content but am still unable to play video. it will try to load and then the pi restarts itself and leaves a crash log. i will do more reading and wait for updates. 
[01_KODI_CRASH.log](https://github.com/Sandmann79/xbmc/files/1691821/01_KODI_CRASH.log)

**Comment by Sandmann79** [comment]
Fixed at 504a9393d0cdab130608dc606829965fd9bb7c34
