### ISSUE TITLE
Audio Latino?

### ISSUE THREAD

**Issue by thetruemachine** [Sandmann79/xbmc#79]
Latin Spanish does not appear in the audio list.
Could someone tell me why?
please.

Thanks for your excellent work guys.

**Comment by Varstahl** [comment]
Maybe it's listed under Spanish? It seems to me that Kodi approximates languages. There should be at least 3 entries per language, at least it works like that in my european tests. What languages should be there that aren't?

Keep in mind that we don't really manage the audio streams, most of it is done by either Kodi or InputStream.Adaptive.

**Comment by thetruemachine** [comment]
In the list of languages of the web of prime video I have Deutsch, English, Spanish (Spain), Spanish (Latin America), Français, Italiano, Português. But in Kodi or InputStream.Adaptive Spanish Latin does not appear.

Thank you for answering so quickly.

**Comment by thetruemachine** [comment]
Incredible my friend, but somehow it is solved. Now I see four audios in Spanish including Latin Spanish.
Thank you very much for your great work.

**Comment by Varstahl** [comment]
No problem. Enjoy :)

**Comment by axlt2002** [comment]
Hi,

I'm posting in this thread because I have a general question related to the audio (I remember to have seen something similar reported in another thread, but I didn't find it again...sorry!).

It is a correct understanding that when a movie/tv show starts I have to manually select the audio track of interest? For exmaple I have tried a couple of movies and one started in german, the second one in spanish. I needed to manually select the italian...

Am I missing something in the settings?

Thanks in advance for any feedback.

**Comment by Varstahl** [comment]
@axlt2002 in the Kodi audio settings (or somewhere around there) you have two options, the first is the preferred audio language, the second is the preferred subtitle language. So if you set it in Kodi, it will automatically pick the right audio track for you. The subtitle auto-pick doesn't quite work yet for unknown reasons, I'm going to investigate that shortly.
