### ISSUE TITLE
Videos not playing on Amazon VOD plugin for Raspberry Pi 3

### ISSUE THREAD

**Issue by nolsen42** [Sandmann79/xbmc#90]
```13:18:33.387 T:1155621616  NOTICE: [Amazon VOD] Player Starting: 0.0/0.0
13:18:34.691 T:1474663152   ERROR: AddOnLog: InputStream Adaptive: Unable to find license;hdcpEnforcementResolutionPixels in JSON string
13:18:34.691 T:1474663152   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
13:18:34.692 T:1474663152   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
13:18:34.693 T:1474663152   ERROR: CVideoPlayer::OpenInputStream - error opening [URL REDACTED]
13:18:34.693 T:1474663152  NOTICE: CVideoPlayer::OnExit()
13:18:34.695 T:1155621616   ERROR: EXCEPTION: XBMC is not playing any media file
13:18:34.702 T:1155621616   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XBMC is not playing any media file
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 3135, in <module>
                                                PlayVideo(args.get('name'), args.get('asin'), args.get('adult'), int(args.get('trailer', '0')), int(args.get('selbitrate', '0')))
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 1588, in PlayVideo
                                                playable = IStreamPlayback(asin, name, trailer, isAdult, extern)
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 1791, in IStreamPlayback
                                                valid_track = validAudioTrack()
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 1844, in validAudioTrack
                                                Log('Player Caching: %s/%s' % (player.getTime(), player.getTotalTime()))
                                            RuntimeError: XBMC is not playing any media file
                                            -->End of Python script error report<--

```

And just to point out, the winevine is working for netflix plugin.

**Comment by Varstahl** [comment]
While we wait for @Sandmann79 let me see if my assumptions are correct: you are using JP/UK/US accounts and apparently none of the video content is working? Did you try multiple videos or just a couple? It always logs `License update not successful`?

**Comment by nolsen42** [comment]
US: Yes
Multiple Videos: So far, Yes
License update: So far, yes.

**Comment by Sandmann79** [comment]
That's almost the same like in #62. 

You have to use the newest available libwidevine.so for Amazon, older versions doesn't work anymore and displaying the `Unable to find license;hdcpEnforcementResolutionPixels` error message.

So remove the entire `/home/osmc/.kodi/userdata/addon_data/script.module.inputstreamhelper` directory and delete this file `/home/osmc/.kodi/cdm/libwidevinecdm.so`. 

If not done yet, you should update OSMC to newest available build.

After that just start any video, so Inputstream Helper can download the libwidevine library.

**Comment by Sandmann79** [comment]
@nolsen42 do you got this fixed?

**Comment by makeITpossible001** [comment]
As nolsen42 mentioned, i had the same error. @Sandmann79 thank u very much this is the solution! :-)

**Comment by sky7176** [comment]
Goodmorning everyone,
I can not get the Amazon VOD plugin to work on my raspberry 3b.

System settings in Italian and Amazon Italian account.

Use Libreelec Kodi 17.6, with inputstream.
I see the list of movies, but if I try to view a movie nothing happens.

I checked the log and I noticed this line:
ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/

with WinSCP I went to check and actually in that path I do not have the folder "inputstream.adaptive", on the contrary the folder I find it in this path:
/storage/.kodi/addons

I'm not an expert on Linux and as a result I have no idea if it is correct, but since I have an error in the log I think there is an anomaly.

This is the piece of log I get when I try to view a movie:
08: 59: 09.896 T: 1944678512 ERROR: Control 55 in window 10025 has been asked to focus, but it can not
08: 59: 36.300 T: 1857024928 NOTICE: [Amazon VOD] Using Host: Cloudfront
08: 59: 36.311 T: 1857024928 NOTICE: [Amazon VOD] checkURL: https://s3-dub.cf.dash.row.aiv-cdn.net/dm/2$YoTm9zGkdT2gy90vCM04DJmgnZ8~/9823/67f1/f007/4b83 -9033-100731c65071 / b2202bb9-90ef-4a3e-94e5-c730c51dc4d2_corrected.mpd
08: 59: 37.036 T: 1857024928 NOTICE: [Amazon VOD] getURL: https://s3-dub.cf.dash.row.aiv-cdn.net/dm/2$YoTm9zGkdT2gy90vCM04DJmgnZ8/9823/67f1/f007/4b83- 9033-100731c65071 / b2202bb9-90ef-4a3e-94e5-c730c51dc4d2_corrected.mpd
08: 59: 38.747 T: 1857024928 NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.0.20.0
08: 59: 38.748 T: 1857024928 NOTICE: [Amazon VOD] Checking AudioTrack
08: 59: 38.813 T: 1944678512 NOTICE: VideoPlayer: Opening: https://s3-dub.cf.dash.row.aiv-cdn.net/dm/2$YoTm9zGkdT2gy90vCM04DJmgnZ8/9823/67f1/f007/4b83-9033- 100731c65071 / b2202bb9-90ef-4a3e-94e5-c730c51dc4d2_corrected.mpd
08: 59: 38.813 T: 1944678512 WARNING: CDVDMessageQueue (player) :: Put MSGQ_NOT_INITIALIZED
08: 59: 38.814 T: 1451226016 NOTICE: Creating InputStream
08: 59: 38.978 T: 1451226016 ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
08: 59: 42.785 T: 1451226016 ERROR: AddOnLog: Adaptive InputStream: Unable to find license; hdcpEnforcementResolutionPixels in JSON string
08: 59: 42.785 T: 1451226016 ERROR: AddOnLog: Adaptive InputStream: License update not successful (no keys)
08: 59: 42.786 T: 1451226016 ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
08: 59: 42.789 T: 1451226016 ERROR: CVideoPlayer :: OpenInputStream - error opening [https://s3-dub.cf.dash.row.aiv-cdn.net/dm/2$YoTm9zGkdT2gy90vCM04DJmgnZ8/9823/67f1/f007/ 4b83-9033-100731c65071 / b2202bb9-90ef-4a3e-94e5-c730c51dc4d2_corrected.mpd]
08: 59: 42.789 T: 1451226016 NOTICE: CVideoPlayer :: OnExit ()
08: 59: 42.790 T: 1944678512 ERROR: Playlist Player: skipping unplayable item: 0, path [plugin: //plugin.video.amazon-test/? Mode = PrimeVideo_Browse & path = root-% 2F% 2F-Film-% 2F% 2F-Film +% E2% 80% 93 + Action + and + adventure - // - 0FFLMNHL25OTTBMQRWJXX0DDX4]
08: 59: 42.815 T: 1944678512 NOTICE: CVideoPlayer :: CloseFile ()
08: 59: 42.815 T: 1944678512 NOTICE: VideoPlayer: waiting for threads to exit
08: 59: 42.815 T: 1944678512 NOTICE: VideoPlayer: finished waiting
08: 59: 42.815 T: 1944678512 NOTICE: CVideoPlayer :: CloseFile ()
08: 59: 42.816 T: 1944678512 NOTICE: VideoPlayer: waiting for threads to exit
08: 59: 42.816 T: 1944678512 NOTICE: VideoPlayer: finished waiting

Mote thank you
Giuseppe

**Comment by Varstahl** [comment]
@sky7176 InputStream.Adaptive with its updates, for the streaming inside Kodi, require Kodi Leia (v18+). Most of the decryption features won't work without Kodi 18. See [https://forum.kodi.tv/showthread.php?tid=298462](https://forum.kodi.tv/showthread.php?tid=298462).

**Comment by Varstahl** [comment]
> `Starting Kodi (17.6 Git:a9a7a20)`

For starters, you should upgrade to Kodi 18. Taken from the readme (and the repo's front page):

> Due changes at Amazons DRM encryption, using Inputstream makes only sense with Kodi 18 alpha builds and up, because the most streams won't play in Kodi 17.

**Comment by redcloverphoenix** [comment]
Same errors from same python scripts, Netflix plugin works fine.

I found a work around. The error happens when you select a video from a folder such as Action & Adventure and it’s indexed something like 1,000 movies. If you find the video you want to watch, go out and search for the title, it might bring up a couple hundred options instead but plays fine.

Running most recent nightly RC of OSMC for Raspberry Pi, most recent plug in version.

**Comment by Varstahl** [comment]
I swear I fixed that like one month or so ago… Could you send me the *.pvcp file, please?

**Comment by redcloverphoenix** [comment]
Sure, sure... uh how? Command line? Copy paste the text? Install a plugin?

**Comment by redcloverphoenix** [comment]
Oh that's all.
[PVCatalogART4WZ8MWBX2Y.zip](https://github.com/Sandmann79/xbmc/files/2710836/PVCatalogART4WZ8MWBX2Y.zip)

**Comment by Varstahl** [comment]
@targyll thanks for the feedback.
@redcloverphoenix as to not clutter this issue, I'm handling your problem in #221.

**Comment by rytecbe** [comment]
Since this topic has not been closed yet I would like to ask here how it comes that i cannot play a lot of movies on my Amazon VOD add-on for Raspberry PI 3b with OSMC installed.
When I click on the movie the OSMC sign is showing like a spinning wheel and then after a while it shows the movie listing again.

**Comment by Varstahl** [comment]
Without the logs it's a bit impossible to tell. You can find info on how to enable debug logging and where to find them in the [FAQ](https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi).

**Comment by Varstahl** [comment]
Closing this as the info contained within are stale and outdated, on top of being no longer relevant.
