### ISSUE TITLE
Fetching new catalog takes long // Cache expires too soon

### ISSUE THREAD

**Issue by KiruDev** [Sandmann79/xbmc#91]
Loading video list takes around a 2-5 mins for each of the folder/sections.
The real issue is once its loaded it caches it. but the cache is maintained for only one day after which it starts loading the video list again from the beginning.

Fix or any workaround is much appreciated. I liked the plugin for what it does - great work.

Here are my configurations:
System: android tv box  (Widevine Supported)
Location : (ROE_EU) - ROW_EU(works but slow), FE- login fails or doesn't load list
Kodi : 18(Leia alpha)
Settings : save cookie: disabled, save password: disabled (Enabling either of them causes login or loading issues)

**Comment by Varstahl** [comment]
It's a well known problem. When I started working on the primevideo.com support I wanted to provide the basic functionalities as fast as possible, and I did just that. There are already plans to drastically improve both caching and loading times, but I've been caught up in real life work and haven't been able to dedicate a lot of time to the project.

In the meantime there are two workarounds:

- Manually edit the expiration time by changing [this line](https://github.com/Sandmann79/xbmc/blob/9872bd9cc0610e99de17f65d671520fb0bd3e7e0/plugin.video.amazon-test/default.py#L441) in default.py (time is expressed in seconds);
- Look for stuff to see via web browser and then use search functionality in the addon.

It's sub-optimal, and trust me, I feel your pain with those loading times, but until I can have a few hours to dedicate to the addon I can't improve it.

**Comment by KiruDev** [comment]
Thanks  Varstahl.

Not sure whether I can update plugin.video.amazon-test/default.y within a android tv box which is not rooted. anyhow will try it and let you.

I'm a developer, but not with kodi plugins, would like to start and contribute to this project.

**Comment by Varstahl** [comment]
> I'm a developer, but not with Kodi plugins, would like to start and contribute to this project.

Was in the same boat when I started. I was thinking about creating a small project section for what's left to develop for the primevideo support portion, as I already know what needs to be done and I just have to actually write the code to do it. Might do it later on if I can't find the time to fix the few remaining stuff.

> Not sure whether I can update plugin.video.amazon-test/default.y within a android tv box which is not rooted. anyhow will try it and let you know.

I quite don't know, I'm only using Kodi in PC environments, Win7 & Debian Linux.

> Is something like lazy loading available in Kodi, where catalog loading happens in background while user can browse the existing list?

Not really. I quite did it in a stupid way at the moment. In theory it's possible though, most of the code is 
there. If you look at the sources (quite messy, I know) you will find an ordered dictionary structure, where catalog objects have a `lazyLoadURL` parameter when the content has to be loaded in a future time. So one would just need to download what's immediately necessary and then launch a detached thread which scans through the entire tree loading URLs one by one, although there another problem arises with information synchronization across threads.

Kodi addons work like a web server backend, so I'm not 100% sure that's the way to do it. At the moment my plan is to detach the catalog with the movie/tv series information, so that we have a refreshing catalog list, and a permanent catalog of movies and episode information, with all the necessary metadata, never refreshing (or refreshing as per user option). That way just the first scan would be lengthy, while all subsequent calls would not have the need to download additional information about thumbnails, fanart, actors and whatnot while building the catalog up.

Now, if only I had the time to actually do it… :D

**Comment by KiruDev** [comment]
It will be great if you can great a TODO list. will try to get started this week and hope lot of developers will join to contribute to this awesome plugin.

I confirm it is not possible to edit default.py with android, it will be good if you can provide configurable parameter in UI where user can enter or adjust a timeout period as temporary workaround, if you have time for this.

**Comment by CGarces** [comment]
@Sandmann79 @Varstahl 
TODO list can be done using the "[projects](https://github.com/Sandmann79/xbmc/projects)" feature.

@KiruDev The app is in the user space, should be possible edit it. Maybe you need to mount the partition as R/W, I asume that you are using adb to acess.

**Comment by CGarces** [comment]
Maybe as workaround, is possible to change the root categories?

Add the category "Watch Next" at the top, like the browser does

-Watch Next TV and Movies
-TV shows
-Movies
-Kids
-Search

So users that are following a TV Show can access to it without load the full catalogue.

**Comment by Varstahl** [comment]
> Maybe as workaround, is possible to change the root categories?

We can add (and possibly subtract) at will, but at the moment the categories match 100% what you see in the main menu of primevideo.com's website. At the current moment, creating a partial "continue watching" is useless because we don't have a separated permanent caching system. I planned to develop it last weekend, but I had fairly severe personal issues and I was unable to.

Basically before even "faking" the watch next, which is possible, we need to split the website catalog from the video URLs and metadata, making the video and metadata cache permanent (unless updated manually by the user), and the catalog refreshing whenever. This will dramatically increase the performances long term.

If I don't get any other emergencies, I should be able to get it done by sunday.
